// Code generated by ent, DO NOT EDIT.

package service

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the service type in the database.
	Label = "service"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldAllowedAuthMethods holds the string denoting the allowed_auth_methods field in the database.
	FieldAllowedAuthMethods = "allowed_auth_methods"
	// FieldCallbackURL holds the string denoting the callback_url field in the database.
	FieldCallbackURL = "callback_url"
	// FieldCurrentTotal holds the string denoting the current_total field in the database.
	FieldCurrentTotal = "current_total"
	// FieldCurrentUpload holds the string denoting the current_upload field in the database.
	FieldCurrentUpload = "current_upload"
	// FieldCurrentDownload holds the string denoting the current_download field in the database.
	FieldCurrentDownload = "current_download"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// Table holds the table name of the service in the database.
	Table = "services"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "services"
	// NodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	NodeInverseTable = "nodes"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "node_id"
)

// Columns holds all SQL columns for service fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldNodeID,
	FieldName,
	FieldProtocol,
	FieldAllowedAuthMethods,
	FieldCallbackURL,
	FieldCurrentTotal,
	FieldCurrentUpload,
	FieldCurrentDownload,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CallbackURLValidator is a validator for the "callback_url" field. It is called by the builders before save.
	CallbackURLValidator func(string) error
	// DefaultCurrentTotal holds the default value on creation for the "current_total" field.
	DefaultCurrentTotal int64
	// CurrentTotalValidator is a validator for the "current_total" field. It is called by the builders before save.
	CurrentTotalValidator func(int64) error
	// DefaultCurrentUpload holds the default value on creation for the "current_upload" field.
	DefaultCurrentUpload int64
	// CurrentUploadValidator is a validator for the "current_upload" field. It is called by the builders before save.
	CurrentUploadValidator func(int64) error
	// DefaultCurrentDownload holds the default value on creation for the "current_download" field.
	DefaultCurrentDownload int64
	// CurrentDownloadValidator is a validator for the "current_download" field. It is called by the builders before save.
	CurrentDownloadValidator func(int64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Protocol defines the type for the "protocol" enum field.
type Protocol string

// Protocol values.
const (
	ProtocolVless       Protocol = "vless"
	ProtocolVmess       Protocol = "vmess"
	ProtocolTrojan      Protocol = "trojan"
	ProtocolShadowsocks Protocol = "shadowsocks"
	ProtocolWireguard   Protocol = "wireguard"
	ProtocolOpenvpn     Protocol = "openvpn"
	ProtocolIpsec       Protocol = "ipsec"
	ProtocolL2tp        Protocol = "l2tp"
	ProtocolPptp        Protocol = "pptp"
	ProtocolPpp         Protocol = "ppp"
	ProtocolSstp        Protocol = "sstp"
	ProtocolSsh         Protocol = "ssh"
	ProtocolRadius      Protocol = "radius"
	ProtocolXray        Protocol = "xray"
	ProtocolSingbox     Protocol = "singbox"
)

func (pr Protocol) String() string {
	return string(pr)
}

// ProtocolValidator is a validator for the "protocol" field enum values. It is called by the builders before save.
func ProtocolValidator(pr Protocol) error {
	switch pr {
	case ProtocolVless, ProtocolVmess, ProtocolTrojan, ProtocolShadowsocks, ProtocolWireguard, ProtocolOpenvpn, ProtocolIpsec, ProtocolL2tp, ProtocolPptp, ProtocolPpp, ProtocolSstp, ProtocolSsh, ProtocolRadius, ProtocolXray, ProtocolSingbox:
		return nil
	default:
		return fmt.Errorf("service: invalid enum value for protocol field: %q", pr)
	}
}

// OrderOption defines the ordering options for the Service queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByCallbackURL orders the results by the callback_url field.
func ByCallbackURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallbackURL, opts...).ToFunc()
}

// ByCurrentTotal orders the results by the current_total field.
func ByCurrentTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentTotal, opts...).ToFunc()
}

// ByCurrentUpload orders the results by the current_upload field.
func ByCurrentUpload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentUpload, opts...).ToFunc()
}

// ByCurrentDownload orders the results by the current_download field.
func ByCurrentDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentDownload, opts...).ToFunc()
}

// ByNodeField orders the results by node field.
func ByNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeStep(), sql.OrderByField(field, opts...))
	}
}
func newNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
	)
}
