// Code generated by ent, DO NOT EDIT.

package service

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/hiddify/hue/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldUpdatedAt, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldNodeID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldName, v))
}

// CallbackURL applies equality check predicate on the "callback_url" field. It's identical to CallbackURLEQ.
func CallbackURL(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCallbackURL, v))
}

// CurrentTotal applies equality check predicate on the "current_total" field. It's identical to CurrentTotalEQ.
func CurrentTotal(v int64) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCurrentTotal, v))
}

// CurrentUpload applies equality check predicate on the "current_upload" field. It's identical to CurrentUploadEQ.
func CurrentUpload(v int64) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCurrentUpload, v))
}

// CurrentDownload applies equality check predicate on the "current_download" field. It's identical to CurrentDownloadEQ.
func CurrentDownload(v int64) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCurrentDownload, v))
}

// ConfigEtag applies equality check predicate on the "config_etag" field. It's identical to ConfigEtagEQ.
func ConfigEtag(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldConfigEtag, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldUpdatedAt, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldNodeID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Service {
	return predicate.Service(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Service {
	return predicate.Service(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Service {
	return predicate.Service(sql.FieldContainsFold(FieldName, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v Protocol) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v Protocol) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...Protocol) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...Protocol) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldProtocol, vs...))
}

// AllowedAuthMethodsIsNil applies the IsNil predicate on the "allowed_auth_methods" field.
func AllowedAuthMethodsIsNil() predicate.Service {
	return predicate.Service(sql.FieldIsNull(FieldAllowedAuthMethods))
}

// AllowedAuthMethodsNotNil applies the NotNil predicate on the "allowed_auth_methods" field.
func AllowedAuthMethodsNotNil() predicate.Service {
	return predicate.Service(sql.FieldNotNull(FieldAllowedAuthMethods))
}

// CallbackURLEQ applies the EQ predicate on the "callback_url" field.
func CallbackURLEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCallbackURL, v))
}

// CallbackURLNEQ applies the NEQ predicate on the "callback_url" field.
func CallbackURLNEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldCallbackURL, v))
}

// CallbackURLIn applies the In predicate on the "callback_url" field.
func CallbackURLIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldCallbackURL, vs...))
}

// CallbackURLNotIn applies the NotIn predicate on the "callback_url" field.
func CallbackURLNotIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldCallbackURL, vs...))
}

// CallbackURLGT applies the GT predicate on the "callback_url" field.
func CallbackURLGT(v string) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldCallbackURL, v))
}

// CallbackURLGTE applies the GTE predicate on the "callback_url" field.
func CallbackURLGTE(v string) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldCallbackURL, v))
}

// CallbackURLLT applies the LT predicate on the "callback_url" field.
func CallbackURLLT(v string) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldCallbackURL, v))
}

// CallbackURLLTE applies the LTE predicate on the "callback_url" field.
func CallbackURLLTE(v string) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldCallbackURL, v))
}

// CallbackURLContains applies the Contains predicate on the "callback_url" field.
func CallbackURLContains(v string) predicate.Service {
	return predicate.Service(sql.FieldContains(FieldCallbackURL, v))
}

// CallbackURLHasPrefix applies the HasPrefix predicate on the "callback_url" field.
func CallbackURLHasPrefix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasPrefix(FieldCallbackURL, v))
}

// CallbackURLHasSuffix applies the HasSuffix predicate on the "callback_url" field.
func CallbackURLHasSuffix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasSuffix(FieldCallbackURL, v))
}

// CallbackURLIsNil applies the IsNil predicate on the "callback_url" field.
func CallbackURLIsNil() predicate.Service {
	return predicate.Service(sql.FieldIsNull(FieldCallbackURL))
}

// CallbackURLNotNil applies the NotNil predicate on the "callback_url" field.
func CallbackURLNotNil() predicate.Service {
	return predicate.Service(sql.FieldNotNull(FieldCallbackURL))
}

// CallbackURLEqualFold applies the EqualFold predicate on the "callback_url" field.
func CallbackURLEqualFold(v string) predicate.Service {
	return predicate.Service(sql.FieldEqualFold(FieldCallbackURL, v))
}

// CallbackURLContainsFold applies the ContainsFold predicate on the "callback_url" field.
func CallbackURLContainsFold(v string) predicate.Service {
	return predicate.Service(sql.FieldContainsFold(FieldCallbackURL, v))
}

// CurrentTotalEQ applies the EQ predicate on the "current_total" field.
func CurrentTotalEQ(v int64) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCurrentTotal, v))
}

// CurrentTotalNEQ applies the NEQ predicate on the "current_total" field.
func CurrentTotalNEQ(v int64) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldCurrentTotal, v))
}

// CurrentTotalIn applies the In predicate on the "current_total" field.
func CurrentTotalIn(vs ...int64) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldCurrentTotal, vs...))
}

// CurrentTotalNotIn applies the NotIn predicate on the "current_total" field.
func CurrentTotalNotIn(vs ...int64) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldCurrentTotal, vs...))
}

// CurrentTotalGT applies the GT predicate on the "current_total" field.
func CurrentTotalGT(v int64) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldCurrentTotal, v))
}

// CurrentTotalGTE applies the GTE predicate on the "current_total" field.
func CurrentTotalGTE(v int64) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldCurrentTotal, v))
}

// CurrentTotalLT applies the LT predicate on the "current_total" field.
func CurrentTotalLT(v int64) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldCurrentTotal, v))
}

// CurrentTotalLTE applies the LTE predicate on the "current_total" field.
func CurrentTotalLTE(v int64) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldCurrentTotal, v))
}

// CurrentUploadEQ applies the EQ predicate on the "current_upload" field.
func CurrentUploadEQ(v int64) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCurrentUpload, v))
}

// CurrentUploadNEQ applies the NEQ predicate on the "current_upload" field.
func CurrentUploadNEQ(v int64) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldCurrentUpload, v))
}

// CurrentUploadIn applies the In predicate on the "current_upload" field.
func CurrentUploadIn(vs ...int64) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldCurrentUpload, vs...))
}

// CurrentUploadNotIn applies the NotIn predicate on the "current_upload" field.
func CurrentUploadNotIn(vs ...int64) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldCurrentUpload, vs...))
}

// CurrentUploadGT applies the GT predicate on the "current_upload" field.
func CurrentUploadGT(v int64) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldCurrentUpload, v))
}

// CurrentUploadGTE applies the GTE predicate on the "current_upload" field.
func CurrentUploadGTE(v int64) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldCurrentUpload, v))
}

// CurrentUploadLT applies the LT predicate on the "current_upload" field.
func CurrentUploadLT(v int64) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldCurrentUpload, v))
}

// CurrentUploadLTE applies the LTE predicate on the "current_upload" field.
func CurrentUploadLTE(v int64) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldCurrentUpload, v))
}

// CurrentDownloadEQ applies the EQ predicate on the "current_download" field.
func CurrentDownloadEQ(v int64) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldCurrentDownload, v))
}

// CurrentDownloadNEQ applies the NEQ predicate on the "current_download" field.
func CurrentDownloadNEQ(v int64) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldCurrentDownload, v))
}

// CurrentDownloadIn applies the In predicate on the "current_download" field.
func CurrentDownloadIn(vs ...int64) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldCurrentDownload, vs...))
}

// CurrentDownloadNotIn applies the NotIn predicate on the "current_download" field.
func CurrentDownloadNotIn(vs ...int64) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldCurrentDownload, vs...))
}

// CurrentDownloadGT applies the GT predicate on the "current_download" field.
func CurrentDownloadGT(v int64) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldCurrentDownload, v))
}

// CurrentDownloadGTE applies the GTE predicate on the "current_download" field.
func CurrentDownloadGTE(v int64) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldCurrentDownload, v))
}

// CurrentDownloadLT applies the LT predicate on the "current_download" field.
func CurrentDownloadLT(v int64) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldCurrentDownload, v))
}

// CurrentDownloadLTE applies the LTE predicate on the "current_download" field.
func CurrentDownloadLTE(v int64) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldCurrentDownload, v))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.Service {
	return predicate.Service(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.Service {
	return predicate.Service(sql.FieldNotNull(FieldConfig))
}

// ConfigEtagEQ applies the EQ predicate on the "config_etag" field.
func ConfigEtagEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldConfigEtag, v))
}

// ConfigEtagNEQ applies the NEQ predicate on the "config_etag" field.
func ConfigEtagNEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldConfigEtag, v))
}

// ConfigEtagIn applies the In predicate on the "config_etag" field.
func ConfigEtagIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldConfigEtag, vs...))
}

// ConfigEtagNotIn applies the NotIn predicate on the "config_etag" field.
func ConfigEtagNotIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldConfigEtag, vs...))
}

// ConfigEtagGT applies the GT predicate on the "config_etag" field.
func ConfigEtagGT(v string) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldConfigEtag, v))
}

// ConfigEtagGTE applies the GTE predicate on the "config_etag" field.
func ConfigEtagGTE(v string) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldConfigEtag, v))
}

// ConfigEtagLT applies the LT predicate on the "config_etag" field.
func ConfigEtagLT(v string) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldConfigEtag, v))
}

// ConfigEtagLTE applies the LTE predicate on the "config_etag" field.
func ConfigEtagLTE(v string) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldConfigEtag, v))
}

// ConfigEtagContains applies the Contains predicate on the "config_etag" field.
func ConfigEtagContains(v string) predicate.Service {
	return predicate.Service(sql.FieldContains(FieldConfigEtag, v))
}

// ConfigEtagHasPrefix applies the HasPrefix predicate on the "config_etag" field.
func ConfigEtagHasPrefix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasPrefix(FieldConfigEtag, v))
}

// ConfigEtagHasSuffix applies the HasSuffix predicate on the "config_etag" field.
func ConfigEtagHasSuffix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasSuffix(FieldConfigEtag, v))
}

// ConfigEtagIsNil applies the IsNil predicate on the "config_etag" field.
func ConfigEtagIsNil() predicate.Service {
	return predicate.Service(sql.FieldIsNull(FieldConfigEtag))
}

// ConfigEtagNotNil applies the NotNil predicate on the "config_etag" field.
func ConfigEtagNotNil() predicate.Service {
	return predicate.Service(sql.FieldNotNull(FieldConfigEtag))
}

// ConfigEtagEqualFold applies the EqualFold predicate on the "config_etag" field.
func ConfigEtagEqualFold(v string) predicate.Service {
	return predicate.Service(sql.FieldEqualFold(FieldConfigEtag, v))
}

// ConfigEtagContainsFold applies the ContainsFold predicate on the "config_etag" field.
func ConfigEtagContainsFold(v string) predicate.Service {
	return predicate.Service(sql.FieldContainsFold(FieldConfigEtag, v))
}

// HasNode applies the HasEdge predicate on the "node" edge.
func HasNode() predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeWith applies the HasEdge predicate on the "node" edge with a given conditions (other predicates).
func HasNodeWith(preds ...predicate.Node) predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := newNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Service) predicate.Service {
	return predicate.Service(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Service) predicate.Service {
	return predicate.Service(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Service) predicate.Service {
	return predicate.Service(sql.NotPredicates(p))
}
