// Code generated by ent, DO NOT EDIT.

package agent

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the agent type in the database.
	Label = "agent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldCurrentTotal holds the string denoting the current_total field in the database.
	FieldCurrentTotal = "current_total"
	// FieldCurrentUpload holds the string denoting the current_upload field in the database.
	FieldCurrentUpload = "current_upload"
	// FieldCurrentDownload holds the string denoting the current_download field in the database.
	FieldCurrentDownload = "current_download"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// Table holds the table name of the agent in the database.
	Table = "agents"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "agents"
	// NodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	NodeInverseTable = "nodes"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "node_id"
)

// Columns holds all SQL columns for agent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldNodeID,
	FieldName,
	FieldKind,
	FieldVersion,
	FieldLastSeenAt,
	FieldCurrentTotal,
	FieldCurrentUpload,
	FieldCurrentDownload,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// DefaultCurrentTotal holds the default value on creation for the "current_total" field.
	DefaultCurrentTotal int64
	// CurrentTotalValidator is a validator for the "current_total" field. It is called by the builders before save.
	CurrentTotalValidator func(int64) error
	// DefaultCurrentUpload holds the default value on creation for the "current_upload" field.
	DefaultCurrentUpload int64
	// CurrentUploadValidator is a validator for the "current_upload" field. It is called by the builders before save.
	CurrentUploadValidator func(int64) error
	// DefaultCurrentDownload holds the default value on creation for the "current_download" field.
	DefaultCurrentDownload int64
	// CurrentDownloadValidator is a validator for the "current_download" field. It is called by the builders before save.
	CurrentDownloadValidator func(int64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindXray      Kind = "xray"
	KindSingbox   Kind = "singbox"
	KindWireguard Kind = "wireguard"
	KindOpenvpn   Kind = "openvpn"
	KindIpsec     Kind = "ipsec"
	KindRadius    Kind = "radius"
	KindSsh       Kind = "ssh"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindXray, KindSingbox, KindWireguard, KindOpenvpn, KindIpsec, KindRadius, KindSsh:
		return nil
	default:
		return fmt.Errorf("agent: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the Agent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByCurrentTotal orders the results by the current_total field.
func ByCurrentTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentTotal, opts...).ToFunc()
}

// ByCurrentUpload orders the results by the current_upload field.
func ByCurrentUpload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentUpload, opts...).ToFunc()
}

// ByCurrentDownload orders the results by the current_download field.
func ByCurrentDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentDownload, opts...).ToFunc()
}

// ByNodeField orders the results by node field.
func ByNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeStep(), sql.OrderByField(field, opts...))
	}
}
func newNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
	)
}
