// Code generated by ent, DO NOT EDIT.

package usageplan

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the usageplan type in the database.
	Label = "usage_plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldTotalLimit holds the string denoting the total_limit field in the database.
	FieldTotalLimit = "total_limit"
	// FieldUploadLimit holds the string denoting the upload_limit field in the database.
	FieldUploadLimit = "upload_limit"
	// FieldDownloadLimit holds the string denoting the download_limit field in the database.
	FieldDownloadLimit = "download_limit"
	// FieldCurrentTotal holds the string denoting the current_total field in the database.
	FieldCurrentTotal = "current_total"
	// FieldCurrentUpload holds the string denoting the current_upload field in the database.
	FieldCurrentUpload = "current_upload"
	// FieldCurrentDownload holds the string denoting the current_download field in the database.
	FieldCurrentDownload = "current_download"
	// FieldMaxConcurrent holds the string denoting the max_concurrent field in the database.
	FieldMaxConcurrent = "max_concurrent"
	// FieldResetMode holds the string denoting the reset_mode field in the database.
	FieldResetMode = "reset_mode"
	// FieldResetAnchor holds the string denoting the reset_anchor field in the database.
	FieldResetAnchor = "reset_anchor"
	// FieldDurationSeconds holds the string denoting the duration_seconds field in the database.
	FieldDurationSeconds = "duration_seconds"
	// FieldStartAt holds the string denoting the start_at field in the database.
	FieldStartAt = "start_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeSubscriber holds the string denoting the subscriber edge name in mutations.
	EdgeSubscriber = "subscriber"
	// Table holds the table name of the usageplan in the database.
	Table = "usage_plans"
	// SubscriberTable is the table that holds the subscriber relation/edge.
	SubscriberTable = "usage_plans"
	// SubscriberInverseTable is the table name for the Subscriber entity.
	// It exists in this package in order to avoid circular dependency with the "subscriber" package.
	SubscriberInverseTable = "subscribers"
	// SubscriberColumn is the table column denoting the subscriber relation/edge.
	SubscriberColumn = "client_id"
)

// Columns holds all SQL columns for usageplan fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldClientID,
	FieldTotalLimit,
	FieldUploadLimit,
	FieldDownloadLimit,
	FieldCurrentTotal,
	FieldCurrentUpload,
	FieldCurrentDownload,
	FieldMaxConcurrent,
	FieldResetMode,
	FieldResetAnchor,
	FieldDurationSeconds,
	FieldStartAt,
	FieldExpiresAt,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTotalLimit holds the default value on creation for the "total_limit" field.
	DefaultTotalLimit int64
	// TotalLimitValidator is a validator for the "total_limit" field. It is called by the builders before save.
	TotalLimitValidator func(int64) error
	// DefaultUploadLimit holds the default value on creation for the "upload_limit" field.
	DefaultUploadLimit int64
	// UploadLimitValidator is a validator for the "upload_limit" field. It is called by the builders before save.
	UploadLimitValidator func(int64) error
	// DefaultDownloadLimit holds the default value on creation for the "download_limit" field.
	DefaultDownloadLimit int64
	// DownloadLimitValidator is a validator for the "download_limit" field. It is called by the builders before save.
	DownloadLimitValidator func(int64) error
	// DefaultCurrentTotal holds the default value on creation for the "current_total" field.
	DefaultCurrentTotal int64
	// CurrentTotalValidator is a validator for the "current_total" field. It is called by the builders before save.
	CurrentTotalValidator func(int64) error
	// DefaultCurrentUpload holds the default value on creation for the "current_upload" field.
	DefaultCurrentUpload int64
	// CurrentUploadValidator is a validator for the "current_upload" field. It is called by the builders before save.
	CurrentUploadValidator func(int64) error
	// DefaultCurrentDownload holds the default value on creation for the "current_download" field.
	DefaultCurrentDownload int64
	// CurrentDownloadValidator is a validator for the "current_download" field. It is called by the builders before save.
	CurrentDownloadValidator func(int64) error
	// DefaultMaxConcurrent holds the default value on creation for the "max_concurrent" field.
	DefaultMaxConcurrent int32
	// MaxConcurrentValidator is a validator for the "max_concurrent" field. It is called by the builders before save.
	MaxConcurrentValidator func(int32) error
	// DefaultDurationSeconds holds the default value on creation for the "duration_seconds" field.
	DefaultDurationSeconds int64
	// DurationSecondsValidator is a validator for the "duration_seconds" field. It is called by the builders before save.
	DurationSecondsValidator func(int64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ResetMode defines the type for the "reset_mode" enum field.
type ResetMode string

// ResetModeNoReset is the default value of the ResetMode enum.
const DefaultResetMode = ResetModeNoReset

// ResetMode values.
const (
	ResetModeNoReset ResetMode = "no_reset"
	ResetModeHourly  ResetMode = "hourly"
	ResetModeDaily   ResetMode = "daily"
	ResetModeWeekly  ResetMode = "weekly"
	ResetModeMonthly ResetMode = "monthly"
	ResetModeYearly  ResetMode = "yearly"
)

func (rm ResetMode) String() string {
	return string(rm)
}

// ResetModeValidator is a validator for the "reset_mode" field enum values. It is called by the builders before save.
func ResetModeValidator(rm ResetMode) error {
	switch rm {
	case ResetModeNoReset, ResetModeHourly, ResetModeDaily, ResetModeWeekly, ResetModeMonthly, ResetModeYearly:
		return nil
	default:
		return fmt.Errorf("usageplan: invalid enum value for reset_mode field: %q", rm)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive         Status = "active"
	StatusExpired        Status = "expired"
	StatusQuotaUsed      Status = "quota_used"
	StatusSuspended      Status = "suspended"
	StatusSessionReached Status = "session_reached"
	StatusPenalty        Status = "penalty"
	StatusInactive       Status = "inactive"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusExpired, StatusQuotaUsed, StatusSuspended, StatusSessionReached, StatusPenalty, StatusInactive:
		return nil
	default:
		return fmt.Errorf("usageplan: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the UsagePlan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByTotalLimit orders the results by the total_limit field.
func ByTotalLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalLimit, opts...).ToFunc()
}

// ByUploadLimit orders the results by the upload_limit field.
func ByUploadLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadLimit, opts...).ToFunc()
}

// ByDownloadLimit orders the results by the download_limit field.
func ByDownloadLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadLimit, opts...).ToFunc()
}

// ByCurrentTotal orders the results by the current_total field.
func ByCurrentTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentTotal, opts...).ToFunc()
}

// ByCurrentUpload orders the results by the current_upload field.
func ByCurrentUpload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentUpload, opts...).ToFunc()
}

// ByCurrentDownload orders the results by the current_download field.
func ByCurrentDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentDownload, opts...).ToFunc()
}

// ByMaxConcurrent orders the results by the max_concurrent field.
func ByMaxConcurrent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxConcurrent, opts...).ToFunc()
}

// ByResetMode orders the results by the reset_mode field.
func ByResetMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetMode, opts...).ToFunc()
}

// ByResetAnchor orders the results by the reset_anchor field.
func ByResetAnchor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetAnchor, opts...).ToFunc()
}

// ByDurationSeconds orders the results by the duration_seconds field.
func ByDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationSeconds, opts...).ToFunc()
}

// ByStartAt orders the results by the start_at field.
func ByStartAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySubscriberField orders the results by subscriber field.
func BySubscriberField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriberStep(), sql.OrderByField(field, opts...))
	}
}
func newSubscriberStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubscriberInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubscriberTable, SubscriberColumn),
	)
}
