// Code generated by ent, DO NOT EDIT.

package usageplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/hiddify/hue/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldUserID, v))
}

// TotalLimit applies equality check predicate on the "total_limit" field. It's identical to TotalLimitEQ.
func TotalLimit(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldTotalLimit, v))
}

// UploadLimit applies equality check predicate on the "upload_limit" field. It's identical to UploadLimitEQ.
func UploadLimit(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldUploadLimit, v))
}

// DownloadLimit applies equality check predicate on the "download_limit" field. It's identical to DownloadLimitEQ.
func DownloadLimit(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldDownloadLimit, v))
}

// CurrentTotal applies equality check predicate on the "current_total" field. It's identical to CurrentTotalEQ.
func CurrentTotal(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldCurrentTotal, v))
}

// CurrentUpload applies equality check predicate on the "current_upload" field. It's identical to CurrentUploadEQ.
func CurrentUpload(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldCurrentUpload, v))
}

// CurrentDownload applies equality check predicate on the "current_download" field. It's identical to CurrentDownloadEQ.
func CurrentDownload(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldCurrentDownload, v))
}

// MaxConcurrent applies equality check predicate on the "max_concurrent" field. It's identical to MaxConcurrentEQ.
func MaxConcurrent(v int32) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldMaxConcurrent, v))
}

// ResetAnchor applies equality check predicate on the "reset_anchor" field. It's identical to ResetAnchorEQ.
func ResetAnchor(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldResetAnchor, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldDurationSeconds, v))
}

// StartAt applies equality check predicate on the "start_at" field. It's identical to StartAtEQ.
func StartAt(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldStartAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldUserID, vs...))
}

// TotalLimitEQ applies the EQ predicate on the "total_limit" field.
func TotalLimitEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldTotalLimit, v))
}

// TotalLimitNEQ applies the NEQ predicate on the "total_limit" field.
func TotalLimitNEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldTotalLimit, v))
}

// TotalLimitIn applies the In predicate on the "total_limit" field.
func TotalLimitIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldTotalLimit, vs...))
}

// TotalLimitNotIn applies the NotIn predicate on the "total_limit" field.
func TotalLimitNotIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldTotalLimit, vs...))
}

// TotalLimitGT applies the GT predicate on the "total_limit" field.
func TotalLimitGT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldTotalLimit, v))
}

// TotalLimitGTE applies the GTE predicate on the "total_limit" field.
func TotalLimitGTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldTotalLimit, v))
}

// TotalLimitLT applies the LT predicate on the "total_limit" field.
func TotalLimitLT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldTotalLimit, v))
}

// TotalLimitLTE applies the LTE predicate on the "total_limit" field.
func TotalLimitLTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldTotalLimit, v))
}

// UploadLimitEQ applies the EQ predicate on the "upload_limit" field.
func UploadLimitEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldUploadLimit, v))
}

// UploadLimitNEQ applies the NEQ predicate on the "upload_limit" field.
func UploadLimitNEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldUploadLimit, v))
}

// UploadLimitIn applies the In predicate on the "upload_limit" field.
func UploadLimitIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldUploadLimit, vs...))
}

// UploadLimitNotIn applies the NotIn predicate on the "upload_limit" field.
func UploadLimitNotIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldUploadLimit, vs...))
}

// UploadLimitGT applies the GT predicate on the "upload_limit" field.
func UploadLimitGT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldUploadLimit, v))
}

// UploadLimitGTE applies the GTE predicate on the "upload_limit" field.
func UploadLimitGTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldUploadLimit, v))
}

// UploadLimitLT applies the LT predicate on the "upload_limit" field.
func UploadLimitLT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldUploadLimit, v))
}

// UploadLimitLTE applies the LTE predicate on the "upload_limit" field.
func UploadLimitLTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldUploadLimit, v))
}

// DownloadLimitEQ applies the EQ predicate on the "download_limit" field.
func DownloadLimitEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldDownloadLimit, v))
}

// DownloadLimitNEQ applies the NEQ predicate on the "download_limit" field.
func DownloadLimitNEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldDownloadLimit, v))
}

// DownloadLimitIn applies the In predicate on the "download_limit" field.
func DownloadLimitIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldDownloadLimit, vs...))
}

// DownloadLimitNotIn applies the NotIn predicate on the "download_limit" field.
func DownloadLimitNotIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldDownloadLimit, vs...))
}

// DownloadLimitGT applies the GT predicate on the "download_limit" field.
func DownloadLimitGT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldDownloadLimit, v))
}

// DownloadLimitGTE applies the GTE predicate on the "download_limit" field.
func DownloadLimitGTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldDownloadLimit, v))
}

// DownloadLimitLT applies the LT predicate on the "download_limit" field.
func DownloadLimitLT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldDownloadLimit, v))
}

// DownloadLimitLTE applies the LTE predicate on the "download_limit" field.
func DownloadLimitLTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldDownloadLimit, v))
}

// CurrentTotalEQ applies the EQ predicate on the "current_total" field.
func CurrentTotalEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldCurrentTotal, v))
}

// CurrentTotalNEQ applies the NEQ predicate on the "current_total" field.
func CurrentTotalNEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldCurrentTotal, v))
}

// CurrentTotalIn applies the In predicate on the "current_total" field.
func CurrentTotalIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldCurrentTotal, vs...))
}

// CurrentTotalNotIn applies the NotIn predicate on the "current_total" field.
func CurrentTotalNotIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldCurrentTotal, vs...))
}

// CurrentTotalGT applies the GT predicate on the "current_total" field.
func CurrentTotalGT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldCurrentTotal, v))
}

// CurrentTotalGTE applies the GTE predicate on the "current_total" field.
func CurrentTotalGTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldCurrentTotal, v))
}

// CurrentTotalLT applies the LT predicate on the "current_total" field.
func CurrentTotalLT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldCurrentTotal, v))
}

// CurrentTotalLTE applies the LTE predicate on the "current_total" field.
func CurrentTotalLTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldCurrentTotal, v))
}

// CurrentUploadEQ applies the EQ predicate on the "current_upload" field.
func CurrentUploadEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldCurrentUpload, v))
}

// CurrentUploadNEQ applies the NEQ predicate on the "current_upload" field.
func CurrentUploadNEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldCurrentUpload, v))
}

// CurrentUploadIn applies the In predicate on the "current_upload" field.
func CurrentUploadIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldCurrentUpload, vs...))
}

// CurrentUploadNotIn applies the NotIn predicate on the "current_upload" field.
func CurrentUploadNotIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldCurrentUpload, vs...))
}

// CurrentUploadGT applies the GT predicate on the "current_upload" field.
func CurrentUploadGT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldCurrentUpload, v))
}

// CurrentUploadGTE applies the GTE predicate on the "current_upload" field.
func CurrentUploadGTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldCurrentUpload, v))
}

// CurrentUploadLT applies the LT predicate on the "current_upload" field.
func CurrentUploadLT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldCurrentUpload, v))
}

// CurrentUploadLTE applies the LTE predicate on the "current_upload" field.
func CurrentUploadLTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldCurrentUpload, v))
}

// CurrentDownloadEQ applies the EQ predicate on the "current_download" field.
func CurrentDownloadEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldCurrentDownload, v))
}

// CurrentDownloadNEQ applies the NEQ predicate on the "current_download" field.
func CurrentDownloadNEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldCurrentDownload, v))
}

// CurrentDownloadIn applies the In predicate on the "current_download" field.
func CurrentDownloadIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldCurrentDownload, vs...))
}

// CurrentDownloadNotIn applies the NotIn predicate on the "current_download" field.
func CurrentDownloadNotIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldCurrentDownload, vs...))
}

// CurrentDownloadGT applies the GT predicate on the "current_download" field.
func CurrentDownloadGT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldCurrentDownload, v))
}

// CurrentDownloadGTE applies the GTE predicate on the "current_download" field.
func CurrentDownloadGTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldCurrentDownload, v))
}

// CurrentDownloadLT applies the LT predicate on the "current_download" field.
func CurrentDownloadLT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldCurrentDownload, v))
}

// CurrentDownloadLTE applies the LTE predicate on the "current_download" field.
func CurrentDownloadLTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldCurrentDownload, v))
}

// MaxConcurrentEQ applies the EQ predicate on the "max_concurrent" field.
func MaxConcurrentEQ(v int32) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldMaxConcurrent, v))
}

// MaxConcurrentNEQ applies the NEQ predicate on the "max_concurrent" field.
func MaxConcurrentNEQ(v int32) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldMaxConcurrent, v))
}

// MaxConcurrentIn applies the In predicate on the "max_concurrent" field.
func MaxConcurrentIn(vs ...int32) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldMaxConcurrent, vs...))
}

// MaxConcurrentNotIn applies the NotIn predicate on the "max_concurrent" field.
func MaxConcurrentNotIn(vs ...int32) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldMaxConcurrent, vs...))
}

// MaxConcurrentGT applies the GT predicate on the "max_concurrent" field.
func MaxConcurrentGT(v int32) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldMaxConcurrent, v))
}

// MaxConcurrentGTE applies the GTE predicate on the "max_concurrent" field.
func MaxConcurrentGTE(v int32) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldMaxConcurrent, v))
}

// MaxConcurrentLT applies the LT predicate on the "max_concurrent" field.
func MaxConcurrentLT(v int32) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldMaxConcurrent, v))
}

// MaxConcurrentLTE applies the LTE predicate on the "max_concurrent" field.
func MaxConcurrentLTE(v int32) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldMaxConcurrent, v))
}

// ResetModeEQ applies the EQ predicate on the "reset_mode" field.
func ResetModeEQ(v ResetMode) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldResetMode, v))
}

// ResetModeNEQ applies the NEQ predicate on the "reset_mode" field.
func ResetModeNEQ(v ResetMode) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldResetMode, v))
}

// ResetModeIn applies the In predicate on the "reset_mode" field.
func ResetModeIn(vs ...ResetMode) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldResetMode, vs...))
}

// ResetModeNotIn applies the NotIn predicate on the "reset_mode" field.
func ResetModeNotIn(vs ...ResetMode) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldResetMode, vs...))
}

// ResetAnchorEQ applies the EQ predicate on the "reset_anchor" field.
func ResetAnchorEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldResetAnchor, v))
}

// ResetAnchorNEQ applies the NEQ predicate on the "reset_anchor" field.
func ResetAnchorNEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldResetAnchor, v))
}

// ResetAnchorIn applies the In predicate on the "reset_anchor" field.
func ResetAnchorIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldResetAnchor, vs...))
}

// ResetAnchorNotIn applies the NotIn predicate on the "reset_anchor" field.
func ResetAnchorNotIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldResetAnchor, vs...))
}

// ResetAnchorGT applies the GT predicate on the "reset_anchor" field.
func ResetAnchorGT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldResetAnchor, v))
}

// ResetAnchorGTE applies the GTE predicate on the "reset_anchor" field.
func ResetAnchorGTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldResetAnchor, v))
}

// ResetAnchorLT applies the LT predicate on the "reset_anchor" field.
func ResetAnchorLT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldResetAnchor, v))
}

// ResetAnchorLTE applies the LTE predicate on the "reset_anchor" field.
func ResetAnchorLTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldResetAnchor, v))
}

// ResetAnchorIsNil applies the IsNil predicate on the "reset_anchor" field.
func ResetAnchorIsNil() predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIsNull(FieldResetAnchor))
}

// ResetAnchorNotNil applies the NotNil predicate on the "reset_anchor" field.
func ResetAnchorNotNil() predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotNull(FieldResetAnchor))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v int64) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldDurationSeconds, v))
}

// StartAtEQ applies the EQ predicate on the "start_at" field.
func StartAtEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldStartAt, v))
}

// StartAtNEQ applies the NEQ predicate on the "start_at" field.
func StartAtNEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldStartAt, v))
}

// StartAtIn applies the In predicate on the "start_at" field.
func StartAtIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldStartAt, vs...))
}

// StartAtNotIn applies the NotIn predicate on the "start_at" field.
func StartAtNotIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldStartAt, vs...))
}

// StartAtGT applies the GT predicate on the "start_at" field.
func StartAtGT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldStartAt, v))
}

// StartAtGTE applies the GTE predicate on the "start_at" field.
func StartAtGTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldStartAt, v))
}

// StartAtLT applies the LT predicate on the "start_at" field.
func StartAtLT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldStartAt, v))
}

// StartAtLTE applies the LTE predicate on the "start_at" field.
func StartAtLTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldStartAt, v))
}

// StartAtIsNil applies the IsNil predicate on the "start_at" field.
func StartAtIsNil() predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIsNull(FieldStartAt))
}

// StartAtNotNil applies the NotNil predicate on the "start_at" field.
func StartAtNotNil() predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotNull(FieldStartAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotNull(FieldExpiresAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UsagePlan {
	return predicate.UsagePlan(sql.FieldNotIn(FieldStatus, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UsagePlan {
	return predicate.UsagePlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UsagePlan {
	return predicate.UsagePlan(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsagePlan) predicate.UsagePlan {
	return predicate.UsagePlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsagePlan) predicate.UsagePlan {
	return predicate.UsagePlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsagePlan) predicate.UsagePlan {
	return predicate.UsagePlan(sql.NotPredicates(p))
}
