// Code generated by ent, DO NOT EDIT.

package refreshtoken

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the refreshtoken type in the database.
	Label = "refresh_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldJti holds the string denoting the jti field in the database.
	FieldJti = "jti"
	// FieldPrincipalKind holds the string denoting the principal_kind field in the database.
	FieldPrincipalKind = "principal_kind"
	// FieldPrincipalID holds the string denoting the principal_id field in the database.
	FieldPrincipalID = "principal_id"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldReplacedBy holds the string denoting the replaced_by field in the database.
	FieldReplacedBy = "replaced_by"
	// FieldOwnerSudo holds the string denoting the owner_sudo field in the database.
	FieldOwnerSudo = "owner_sudo"
	// Table holds the table name of the refreshtoken in the database.
	Table = "refresh_tokens"
)

// Columns holds all SQL columns for refreshtoken fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldJti,
	FieldPrincipalKind,
	FieldPrincipalID,
	FieldExpiresAt,
	FieldRevokedAt,
	FieldReplacedBy,
	FieldOwnerSudo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// JtiValidator is a validator for the "jti" field. It is called by the builders before save.
	JtiValidator func(string) error
	// PrincipalIDValidator is a validator for the "principal_id" field. It is called by the builders before save.
	PrincipalIDValidator func(string) error
	// ReplacedByValidator is a validator for the "replaced_by" field. It is called by the builders before save.
	ReplacedByValidator func(string) error
	// DefaultOwnerSudo holds the default value on creation for the "owner_sudo" field.
	DefaultOwnerSudo bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PrincipalKind defines the type for the "principal_kind" enum field.
type PrincipalKind string

// PrincipalKind values.
const (
	PrincipalKindClient   PrincipalKind = "client"
	PrincipalKindReseller PrincipalKind = "reseller"
	PrincipalKindOwner    PrincipalKind = "owner"
)

func (pk PrincipalKind) String() string {
	return string(pk)
}

// PrincipalKindValidator is a validator for the "principal_kind" field enum values. It is called by the builders before save.
func PrincipalKindValidator(pk PrincipalKind) error {
	switch pk {
	case PrincipalKindClient, PrincipalKindReseller, PrincipalKindOwner:
		return nil
	default:
		return fmt.Errorf("refreshtoken: invalid enum value for principal_kind field: %q", pk)
	}
}

// OrderOption defines the ordering options for the RefreshToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByJti orders the results by the jti field.
func ByJti(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJti, opts...).ToFunc()
}

// ByPrincipalKind orders the results by the principal_kind field.
func ByPrincipalKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalKind, opts...).ToFunc()
}

// ByPrincipalID orders the results by the principal_id field.
func ByPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByReplacedBy orders the results by the replaced_by field.
func ByReplacedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplacedBy, opts...).ToFunc()
}

// ByOwnerSudo orders the results by the owner_sudo field.
func ByOwnerSudo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerSudo, opts...).ToFunc()
}
