// Code generated by ent, DO NOT EDIT.

package usagereport

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the usagereport type in the database.
	Label = "usage_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldUpload holds the string denoting the upload field in the database.
	FieldUpload = "upload"
	// FieldDownload holds the string denoting the download field in the database.
	FieldDownload = "download"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldTs holds the string denoting the ts field in the database.
	FieldTs = "ts"
	// Table holds the table name of the usagereport in the database.
	Table = "usage_reports"
)

// Columns holds all SQL columns for usagereport fields.
var Columns = []string{
	FieldID,
	FieldClientID,
	FieldNodeID,
	FieldAgentID,
	FieldUpload,
	FieldDownload,
	FieldSessionID,
	FieldTags,
	FieldTs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUpload holds the default value on creation for the "upload" field.
	DefaultUpload int64
	// UploadValidator is a validator for the "upload" field. It is called by the builders before save.
	UploadValidator func(int64) error
	// DefaultDownload holds the default value on creation for the "download" field.
	DefaultDownload int64
	// DownloadValidator is a validator for the "download" field. It is called by the builders before save.
	DownloadValidator func(int64) error
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the UsageReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByUpload orders the results by the upload field.
func ByUpload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpload, opts...).ToFunc()
}

// ByDownload orders the results by the download field.
func ByDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownload, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByTs orders the results by the ts field.
func ByTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTs, opts...).ToFunc()
}
