// Code generated by ent, DO NOT EDIT.

package usagereport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hiddify/hue/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLTE(FieldID, id))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldClientID, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldNodeID, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldAgentID, v))
}

// Upload applies equality check predicate on the "upload" field. It's identical to UploadEQ.
func Upload(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldUpload, v))
}

// Download applies equality check predicate on the "download" field. It's identical to DownloadEQ.
func Download(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldDownload, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldSessionID, v))
}

// Ts applies equality check predicate on the "ts" field. It's identical to TsEQ.
func Ts(v time.Time) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldTs, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLTE(FieldClientID, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDIsNil applies the IsNil predicate on the "node_id" field.
func NodeIDIsNil() predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIsNull(FieldNodeID))
}

// NodeIDNotNil applies the NotNil predicate on the "node_id" field.
func NodeIDNotNil() predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotNull(FieldNodeID))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDGT applies the GT predicate on the "agent_id" field.
func AgentIDGT(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGT(FieldAgentID, v))
}

// AgentIDGTE applies the GTE predicate on the "agent_id" field.
func AgentIDGTE(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGTE(FieldAgentID, v))
}

// AgentIDLT applies the LT predicate on the "agent_id" field.
func AgentIDLT(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLT(FieldAgentID, v))
}

// AgentIDLTE applies the LTE predicate on the "agent_id" field.
func AgentIDLTE(v uuid.UUID) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLTE(FieldAgentID, v))
}

// AgentIDIsNil applies the IsNil predicate on the "agent_id" field.
func AgentIDIsNil() predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIsNull(FieldAgentID))
}

// AgentIDNotNil applies the NotNil predicate on the "agent_id" field.
func AgentIDNotNil() predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotNull(FieldAgentID))
}

// UploadEQ applies the EQ predicate on the "upload" field.
func UploadEQ(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldUpload, v))
}

// UploadNEQ applies the NEQ predicate on the "upload" field.
func UploadNEQ(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNEQ(FieldUpload, v))
}

// UploadIn applies the In predicate on the "upload" field.
func UploadIn(vs ...int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIn(FieldUpload, vs...))
}

// UploadNotIn applies the NotIn predicate on the "upload" field.
func UploadNotIn(vs ...int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotIn(FieldUpload, vs...))
}

// UploadGT applies the GT predicate on the "upload" field.
func UploadGT(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGT(FieldUpload, v))
}

// UploadGTE applies the GTE predicate on the "upload" field.
func UploadGTE(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGTE(FieldUpload, v))
}

// UploadLT applies the LT predicate on the "upload" field.
func UploadLT(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLT(FieldUpload, v))
}

// UploadLTE applies the LTE predicate on the "upload" field.
func UploadLTE(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLTE(FieldUpload, v))
}

// DownloadEQ applies the EQ predicate on the "download" field.
func DownloadEQ(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldDownload, v))
}

// DownloadNEQ applies the NEQ predicate on the "download" field.
func DownloadNEQ(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNEQ(FieldDownload, v))
}

// DownloadIn applies the In predicate on the "download" field.
func DownloadIn(vs ...int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIn(FieldDownload, vs...))
}

// DownloadNotIn applies the NotIn predicate on the "download" field.
func DownloadNotIn(vs ...int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotIn(FieldDownload, vs...))
}

// DownloadGT applies the GT predicate on the "download" field.
func DownloadGT(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGT(FieldDownload, v))
}

// DownloadGTE applies the GTE predicate on the "download" field.
func DownloadGTE(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGTE(FieldDownload, v))
}

// DownloadLT applies the LT predicate on the "download" field.
func DownloadLT(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLT(FieldDownload, v))
}

// DownloadLTE applies the LTE predicate on the "download" field.
func DownloadLTE(v int64) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLTE(FieldDownload, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDIsNil applies the IsNil predicate on the "session_id" field.
func SessionIDIsNil() predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIsNull(FieldSessionID))
}

// SessionIDNotNil applies the NotNil predicate on the "session_id" field.
func SessionIDNotNil() predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotNull(FieldSessionID))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldContainsFold(FieldSessionID, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotNull(FieldTags))
}

// TsEQ applies the EQ predicate on the "ts" field.
func TsEQ(v time.Time) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldEQ(FieldTs, v))
}

// TsNEQ applies the NEQ predicate on the "ts" field.
func TsNEQ(v time.Time) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNEQ(FieldTs, v))
}

// TsIn applies the In predicate on the "ts" field.
func TsIn(vs ...time.Time) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldIn(FieldTs, vs...))
}

// TsNotIn applies the NotIn predicate on the "ts" field.
func TsNotIn(vs ...time.Time) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldNotIn(FieldTs, vs...))
}

// TsGT applies the GT predicate on the "ts" field.
func TsGT(v time.Time) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGT(FieldTs, v))
}

// TsGTE applies the GTE predicate on the "ts" field.
func TsGTE(v time.Time) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldGTE(FieldTs, v))
}

// TsLT applies the LT predicate on the "ts" field.
func TsLT(v time.Time) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLT(FieldTs, v))
}

// TsLTE applies the LTE predicate on the "ts" field.
func TsLTE(v time.Time) predicate.UsageReport {
	return predicate.UsageReport(sql.FieldLTE(FieldTs, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageReport) predicate.UsageReport {
	return predicate.UsageReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageReport) predicate.UsageReport {
	return predicate.UsageReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageReport) predicate.UsageReport {
	return predicate.UsageReport(sql.NotPredicates(p))
}
