// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldPrivateKeyEnc holds the string denoting the private_key_enc field in the database.
	FieldPrivateKeyEnc = "private_key_enc"
	// FieldCaCerts holds the string denoting the ca_certs field in the database.
	FieldCaCerts = "ca_certs"
	// FieldAllowedDevices holds the string denoting the allowed_devices field in the database.
	FieldAllowedDevices = "allowed_devices"
	// FieldGroups holds the string denoting the groups field in the database.
	FieldGroups = "groups"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldFirstConnectionAt holds the string denoting the first_connection_at field in the database.
	FieldFirstConnectionAt = "first_connection_at"
	// FieldLastConnectionAt holds the string denoting the last_connection_at field in the database.
	FieldLastConnectionAt = "last_connection_at"
	// FieldManagerID holds the string denoting the manager_id field in the database.
	FieldManagerID = "manager_id"
	// FieldActivePlanID holds the string denoting the active_plan_id field in the database.
	FieldActivePlanID = "active_plan_id"
	// EdgeManager holds the string denoting the manager edge name in mutations.
	EdgeManager = "manager"
	// EdgeUsagePlans holds the string denoting the usage_plans edge name in mutations.
	EdgeUsagePlans = "usage_plans"
	// EdgeActivePlan holds the string denoting the active_plan edge name in mutations.
	EdgeActivePlan = "active_plan"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ManagerTable is the table that holds the manager relation/edge.
	ManagerTable = "users"
	// ManagerInverseTable is the table name for the Manager entity.
	// It exists in this package in order to avoid circular dependency with the "manager" package.
	ManagerInverseTable = "managers"
	// ManagerColumn is the table column denoting the manager relation/edge.
	ManagerColumn = "manager_id"
	// UsagePlansTable is the table that holds the usage_plans relation/edge.
	UsagePlansTable = "usage_plans"
	// UsagePlansInverseTable is the table name for the UsagePlan entity.
	// It exists in this package in order to avoid circular dependency with the "usageplan" package.
	UsagePlansInverseTable = "usage_plans"
	// UsagePlansColumn is the table column denoting the usage_plans relation/edge.
	UsagePlansColumn = "user_id"
	// ActivePlanTable is the table that holds the active_plan relation/edge.
	ActivePlanTable = "users"
	// ActivePlanInverseTable is the table name for the UsagePlan entity.
	// It exists in this package in order to avoid circular dependency with the "usageplan" package.
	ActivePlanInverseTable = "usage_plans"
	// ActivePlanColumn is the table column denoting the active_plan relation/edge.
	ActivePlanColumn = "active_plan_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUsername,
	FieldPasswordHash,
	FieldPublicKey,
	FieldPrivateKeyEnc,
	FieldCaCerts,
	FieldAllowedDevices,
	FieldGroups,
	FieldStatus,
	FieldMetadata,
	FieldFirstConnectionAt,
	FieldLastConnectionAt,
	FieldManagerID,
	FieldActivePlanID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	PublicKeyValidator func(string) error
	// PrivateKeyEncValidator is a validator for the "private_key_enc" field. It is called by the builders before save.
	PrivateKeyEncValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusSuspended Status = "suspended"
	StatusExpired   Status = "expired"
	StatusQuotaUsed Status = "quota_used"
	StatusPenalty   Status = "penalty"
	StatusInactive  Status = "inactive"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusSuspended, StatusExpired, StatusQuotaUsed, StatusPenalty, StatusInactive:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByPublicKey orders the results by the public_key field.
func ByPublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKey, opts...).ToFunc()
}

// ByPrivateKeyEnc orders the results by the private_key_enc field.
func ByPrivateKeyEnc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivateKeyEnc, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFirstConnectionAt orders the results by the first_connection_at field.
func ByFirstConnectionAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstConnectionAt, opts...).ToFunc()
}

// ByLastConnectionAt orders the results by the last_connection_at field.
func ByLastConnectionAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastConnectionAt, opts...).ToFunc()
}

// ByManagerID orders the results by the manager_id field.
func ByManagerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagerID, opts...).ToFunc()
}

// ByActivePlanID orders the results by the active_plan_id field.
func ByActivePlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivePlanID, opts...).ToFunc()
}

// ByManagerField orders the results by manager field.
func ByManagerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagerStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsagePlansCount orders the results by usage_plans count.
func ByUsagePlansCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsagePlansStep(), opts...)
	}
}

// ByUsagePlans orders the results by usage_plans terms.
func ByUsagePlans(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsagePlansStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByActivePlanField orders the results by active_plan field.
func ByActivePlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActivePlanStep(), sql.OrderByField(field, opts...))
	}
}
func newManagerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ManagerTable, ManagerColumn),
	)
}
func newUsagePlansStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsagePlansInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsagePlansTable, UsagePlansColumn),
	)
}
func newActivePlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActivePlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ActivePlanTable, ActivePlanColumn),
	)
}
