// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/hiddify/hue/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPublicKey, v))
}

// PrivateKeyEnc applies equality check predicate on the "private_key_enc" field. It's identical to PrivateKeyEncEQ.
func PrivateKeyEnc(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPrivateKeyEnc, v))
}

// FirstConnectionAt applies equality check predicate on the "first_connection_at" field. It's identical to FirstConnectionAtEQ.
func FirstConnectionAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFirstConnectionAt, v))
}

// LastConnectionAt applies equality check predicate on the "last_connection_at" field. It's identical to LastConnectionAtEQ.
func LastConnectionAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastConnectionAt, v))
}

// ManagerID applies equality check predicate on the "manager_id" field. It's identical to ManagerIDEQ.
func ManagerID(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldManagerID, v))
}

// ActivePlanID applies equality check predicate on the "active_plan_id" field. It's identical to ActivePlanIDEQ.
func ActivePlanID(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldActivePlanID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashIsNil applies the IsNil predicate on the "password_hash" field.
func PasswordHashIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPasswordHash))
}

// PasswordHashNotNil applies the NotNil predicate on the "password_hash" field.
func PasswordHashNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPasswordHash))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPasswordHash, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "public_key" field.
func PublicKeyContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "public_key" field.
func PublicKeyHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "public_key" field.
func PublicKeyHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyIsNil applies the IsNil predicate on the "public_key" field.
func PublicKeyIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPublicKey))
}

// PublicKeyNotNil applies the NotNil predicate on the "public_key" field.
func PublicKeyNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPublicKey))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "public_key" field.
func PublicKeyEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "public_key" field.
func PublicKeyContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPublicKey, v))
}

// PrivateKeyEncEQ applies the EQ predicate on the "private_key_enc" field.
func PrivateKeyEncEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncNEQ applies the NEQ predicate on the "private_key_enc" field.
func PrivateKeyEncNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncIn applies the In predicate on the "private_key_enc" field.
func PrivateKeyEncIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPrivateKeyEnc, vs...))
}

// PrivateKeyEncNotIn applies the NotIn predicate on the "private_key_enc" field.
func PrivateKeyEncNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPrivateKeyEnc, vs...))
}

// PrivateKeyEncGT applies the GT predicate on the "private_key_enc" field.
func PrivateKeyEncGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncGTE applies the GTE predicate on the "private_key_enc" field.
func PrivateKeyEncGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncLT applies the LT predicate on the "private_key_enc" field.
func PrivateKeyEncLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncLTE applies the LTE predicate on the "private_key_enc" field.
func PrivateKeyEncLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncContains applies the Contains predicate on the "private_key_enc" field.
func PrivateKeyEncContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncHasPrefix applies the HasPrefix predicate on the "private_key_enc" field.
func PrivateKeyEncHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncHasSuffix applies the HasSuffix predicate on the "private_key_enc" field.
func PrivateKeyEncHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncIsNil applies the IsNil predicate on the "private_key_enc" field.
func PrivateKeyEncIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPrivateKeyEnc))
}

// PrivateKeyEncNotNil applies the NotNil predicate on the "private_key_enc" field.
func PrivateKeyEncNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPrivateKeyEnc))
}

// PrivateKeyEncEqualFold applies the EqualFold predicate on the "private_key_enc" field.
func PrivateKeyEncEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPrivateKeyEnc, v))
}

// PrivateKeyEncContainsFold applies the ContainsFold predicate on the "private_key_enc" field.
func PrivateKeyEncContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPrivateKeyEnc, v))
}

// CaCertsIsNil applies the IsNil predicate on the "ca_certs" field.
func CaCertsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldCaCerts))
}

// CaCertsNotNil applies the NotNil predicate on the "ca_certs" field.
func CaCertsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldCaCerts))
}

// AllowedDevicesIsNil applies the IsNil predicate on the "allowed_devices" field.
func AllowedDevicesIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAllowedDevices))
}

// AllowedDevicesNotNil applies the NotNil predicate on the "allowed_devices" field.
func AllowedDevicesNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAllowedDevices))
}

// GroupsIsNil applies the IsNil predicate on the "groups" field.
func GroupsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldGroups))
}

// GroupsNotNil applies the NotNil predicate on the "groups" field.
func GroupsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldGroups))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.User {
	return predicate.User(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.User {
	return predicate.User(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldStatus, vs...))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldMetadata))
}

// FirstConnectionAtEQ applies the EQ predicate on the "first_connection_at" field.
func FirstConnectionAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFirstConnectionAt, v))
}

// FirstConnectionAtNEQ applies the NEQ predicate on the "first_connection_at" field.
func FirstConnectionAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldFirstConnectionAt, v))
}

// FirstConnectionAtIn applies the In predicate on the "first_connection_at" field.
func FirstConnectionAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldFirstConnectionAt, vs...))
}

// FirstConnectionAtNotIn applies the NotIn predicate on the "first_connection_at" field.
func FirstConnectionAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldFirstConnectionAt, vs...))
}

// FirstConnectionAtGT applies the GT predicate on the "first_connection_at" field.
func FirstConnectionAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldFirstConnectionAt, v))
}

// FirstConnectionAtGTE applies the GTE predicate on the "first_connection_at" field.
func FirstConnectionAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldFirstConnectionAt, v))
}

// FirstConnectionAtLT applies the LT predicate on the "first_connection_at" field.
func FirstConnectionAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldFirstConnectionAt, v))
}

// FirstConnectionAtLTE applies the LTE predicate on the "first_connection_at" field.
func FirstConnectionAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldFirstConnectionAt, v))
}

// FirstConnectionAtIsNil applies the IsNil predicate on the "first_connection_at" field.
func FirstConnectionAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldFirstConnectionAt))
}

// FirstConnectionAtNotNil applies the NotNil predicate on the "first_connection_at" field.
func FirstConnectionAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldFirstConnectionAt))
}

// LastConnectionAtEQ applies the EQ predicate on the "last_connection_at" field.
func LastConnectionAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastConnectionAt, v))
}

// LastConnectionAtNEQ applies the NEQ predicate on the "last_connection_at" field.
func LastConnectionAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastConnectionAt, v))
}

// LastConnectionAtIn applies the In predicate on the "last_connection_at" field.
func LastConnectionAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastConnectionAt, vs...))
}

// LastConnectionAtNotIn applies the NotIn predicate on the "last_connection_at" field.
func LastConnectionAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastConnectionAt, vs...))
}

// LastConnectionAtGT applies the GT predicate on the "last_connection_at" field.
func LastConnectionAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastConnectionAt, v))
}

// LastConnectionAtGTE applies the GTE predicate on the "last_connection_at" field.
func LastConnectionAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastConnectionAt, v))
}

// LastConnectionAtLT applies the LT predicate on the "last_connection_at" field.
func LastConnectionAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastConnectionAt, v))
}

// LastConnectionAtLTE applies the LTE predicate on the "last_connection_at" field.
func LastConnectionAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastConnectionAt, v))
}

// LastConnectionAtIsNil applies the IsNil predicate on the "last_connection_at" field.
func LastConnectionAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldLastConnectionAt))
}

// LastConnectionAtNotNil applies the NotNil predicate on the "last_connection_at" field.
func LastConnectionAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldLastConnectionAt))
}

// ManagerIDEQ applies the EQ predicate on the "manager_id" field.
func ManagerIDEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldManagerID, v))
}

// ManagerIDNEQ applies the NEQ predicate on the "manager_id" field.
func ManagerIDNEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldManagerID, v))
}

// ManagerIDIn applies the In predicate on the "manager_id" field.
func ManagerIDIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldManagerID, vs...))
}

// ManagerIDNotIn applies the NotIn predicate on the "manager_id" field.
func ManagerIDNotIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldManagerID, vs...))
}

// ManagerIDIsNil applies the IsNil predicate on the "manager_id" field.
func ManagerIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldManagerID))
}

// ManagerIDNotNil applies the NotNil predicate on the "manager_id" field.
func ManagerIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldManagerID))
}

// ActivePlanIDEQ applies the EQ predicate on the "active_plan_id" field.
func ActivePlanIDEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldActivePlanID, v))
}

// ActivePlanIDNEQ applies the NEQ predicate on the "active_plan_id" field.
func ActivePlanIDNEQ(v uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldActivePlanID, v))
}

// ActivePlanIDIn applies the In predicate on the "active_plan_id" field.
func ActivePlanIDIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldActivePlanID, vs...))
}

// ActivePlanIDNotIn applies the NotIn predicate on the "active_plan_id" field.
func ActivePlanIDNotIn(vs ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldActivePlanID, vs...))
}

// ActivePlanIDIsNil applies the IsNil predicate on the "active_plan_id" field.
func ActivePlanIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldActivePlanID))
}

// ActivePlanIDNotNil applies the NotNil predicate on the "active_plan_id" field.
func ActivePlanIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldActivePlanID))
}

// HasManager applies the HasEdge predicate on the "manager" edge.
func HasManager() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ManagerTable, ManagerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasManagerWith applies the HasEdge predicate on the "manager" edge with a given conditions (other predicates).
func HasManagerWith(preds ...predicate.Manager) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newManagerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsagePlans applies the HasEdge predicate on the "usage_plans" edge.
func HasUsagePlans() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsagePlansTable, UsagePlansColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsagePlansWith applies the HasEdge predicate on the "usage_plans" edge with a given conditions (other predicates).
func HasUsagePlansWith(preds ...predicate.UsagePlan) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newUsagePlansStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActivePlan applies the HasEdge predicate on the "active_plan" edge.
func HasActivePlan() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ActivePlanTable, ActivePlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActivePlanWith applies the HasEdge predicate on the "active_plan" edge with a given conditions (other predicates).
func HasActivePlanWith(preds ...predicate.UsagePlan) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newActivePlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
