// Code generated by ent, DO NOT EDIT.

package subscriber

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the subscriber type in the database.
	Label = "subscriber"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPasswordCiphertext holds the string denoting the password_ciphertext field in the database.
	FieldPasswordCiphertext = "password_ciphertext"
	// FieldPasswordKeyID holds the string denoting the password_key_id field in the database.
	FieldPasswordKeyID = "password_key_id"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldPrivateKeyCiphertext holds the string denoting the private_key_ciphertext field in the database.
	FieldPrivateKeyCiphertext = "private_key_ciphertext"
	// FieldCaCerts holds the string denoting the ca_certs field in the database.
	FieldCaCerts = "ca_certs"
	// FieldAllowedDevices holds the string denoting the allowed_devices field in the database.
	FieldAllowedDevices = "allowed_devices"
	// FieldGroups holds the string denoting the groups field in the database.
	FieldGroups = "groups"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldFirstConnectionAt holds the string denoting the first_connection_at field in the database.
	FieldFirstConnectionAt = "first_connection_at"
	// FieldLastConnectionAt holds the string denoting the last_connection_at field in the database.
	FieldLastConnectionAt = "last_connection_at"
	// FieldResellerID holds the string denoting the reseller_id field in the database.
	FieldResellerID = "reseller_id"
	// FieldActivePlanID holds the string denoting the active_plan_id field in the database.
	FieldActivePlanID = "active_plan_id"
	// EdgeReseller holds the string denoting the reseller edge name in mutations.
	EdgeReseller = "reseller"
	// EdgeUsagePlans holds the string denoting the usage_plans edge name in mutations.
	EdgeUsagePlans = "usage_plans"
	// EdgeActivePlan holds the string denoting the active_plan edge name in mutations.
	EdgeActivePlan = "active_plan"
	// Table holds the table name of the subscriber in the database.
	Table = "subscribers"
	// ResellerTable is the table that holds the reseller relation/edge.
	ResellerTable = "subscribers"
	// ResellerInverseTable is the table name for the Reseller entity.
	// It exists in this package in order to avoid circular dependency with the "reseller" package.
	ResellerInverseTable = "resellers"
	// ResellerColumn is the table column denoting the reseller relation/edge.
	ResellerColumn = "reseller_id"
	// UsagePlansTable is the table that holds the usage_plans relation/edge.
	UsagePlansTable = "usage_plans"
	// UsagePlansInverseTable is the table name for the UsagePlan entity.
	// It exists in this package in order to avoid circular dependency with the "usageplan" package.
	UsagePlansInverseTable = "usage_plans"
	// UsagePlansColumn is the table column denoting the usage_plans relation/edge.
	UsagePlansColumn = "client_id"
	// ActivePlanTable is the table that holds the active_plan relation/edge.
	ActivePlanTable = "subscribers"
	// ActivePlanInverseTable is the table name for the UsagePlan entity.
	// It exists in this package in order to avoid circular dependency with the "usageplan" package.
	ActivePlanInverseTable = "usage_plans"
	// ActivePlanColumn is the table column denoting the active_plan relation/edge.
	ActivePlanColumn = "active_plan_id"
)

// Columns holds all SQL columns for subscriber fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUsername,
	FieldPasswordCiphertext,
	FieldPasswordKeyID,
	FieldPublicKey,
	FieldPrivateKeyCiphertext,
	FieldCaCerts,
	FieldAllowedDevices,
	FieldGroups,
	FieldStatus,
	FieldMetadata,
	FieldFirstConnectionAt,
	FieldLastConnectionAt,
	FieldResellerID,
	FieldActivePlanID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultPasswordKeyID holds the default value on creation for the "password_key_id" field.
	DefaultPasswordKeyID uint8
	// PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	PublicKeyValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusSuspended Status = "suspended"
	StatusExpired   Status = "expired"
	StatusQuotaUsed Status = "quota_used"
	StatusPenalty   Status = "penalty"
	StatusInactive  Status = "inactive"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusSuspended, StatusExpired, StatusQuotaUsed, StatusPenalty, StatusInactive:
		return nil
	default:
		return fmt.Errorf("subscriber: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Subscriber queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPasswordKeyID orders the results by the password_key_id field.
func ByPasswordKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordKeyID, opts...).ToFunc()
}

// ByPublicKey orders the results by the public_key field.
func ByPublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFirstConnectionAt orders the results by the first_connection_at field.
func ByFirstConnectionAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstConnectionAt, opts...).ToFunc()
}

// ByLastConnectionAt orders the results by the last_connection_at field.
func ByLastConnectionAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastConnectionAt, opts...).ToFunc()
}

// ByResellerID orders the results by the reseller_id field.
func ByResellerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResellerID, opts...).ToFunc()
}

// ByActivePlanID orders the results by the active_plan_id field.
func ByActivePlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivePlanID, opts...).ToFunc()
}

// ByResellerField orders the results by reseller field.
func ByResellerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResellerStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsagePlansCount orders the results by usage_plans count.
func ByUsagePlansCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsagePlansStep(), opts...)
	}
}

// ByUsagePlans orders the results by usage_plans terms.
func ByUsagePlans(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsagePlansStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByActivePlanField orders the results by active_plan field.
func ByActivePlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActivePlanStep(), sql.OrderByField(field, opts...))
	}
}
func newResellerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResellerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ResellerTable, ResellerColumn),
	)
}
func newUsagePlansStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsagePlansInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsagePlansTable, UsagePlansColumn),
	)
}
func newActivePlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActivePlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ActivePlanTable, ActivePlanColumn),
	)
}
