// Code generated by ent, DO NOT EDIT.

package subscriber

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/hiddify/hue/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldUpdatedAt, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldUsername, v))
}

// PasswordCiphertext applies equality check predicate on the "password_ciphertext" field. It's identical to PasswordCiphertextEQ.
func PasswordCiphertext(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldPasswordCiphertext, v))
}

// PasswordKeyID applies equality check predicate on the "password_key_id" field. It's identical to PasswordKeyIDEQ.
func PasswordKeyID(v uint8) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldPasswordKeyID, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldPublicKey, v))
}

// PrivateKeyCiphertext applies equality check predicate on the "private_key_ciphertext" field. It's identical to PrivateKeyCiphertextEQ.
func PrivateKeyCiphertext(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldPrivateKeyCiphertext, v))
}

// FirstConnectionAt applies equality check predicate on the "first_connection_at" field. It's identical to FirstConnectionAtEQ.
func FirstConnectionAt(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldFirstConnectionAt, v))
}

// LastConnectionAt applies equality check predicate on the "last_connection_at" field. It's identical to LastConnectionAtEQ.
func LastConnectionAt(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldLastConnectionAt, v))
}

// ResellerID applies equality check predicate on the "reseller_id" field. It's identical to ResellerIDEQ.
func ResellerID(v uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldResellerID, v))
}

// ActivePlanID applies equality check predicate on the "active_plan_id" field. It's identical to ActivePlanIDEQ.
func ActivePlanID(v uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldActivePlanID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldUpdatedAt, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordCiphertextEQ applies the EQ predicate on the "password_ciphertext" field.
func PasswordCiphertextEQ(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldPasswordCiphertext, v))
}

// PasswordCiphertextNEQ applies the NEQ predicate on the "password_ciphertext" field.
func PasswordCiphertextNEQ(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldPasswordCiphertext, v))
}

// PasswordCiphertextIn applies the In predicate on the "password_ciphertext" field.
func PasswordCiphertextIn(vs ...[]byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldPasswordCiphertext, vs...))
}

// PasswordCiphertextNotIn applies the NotIn predicate on the "password_ciphertext" field.
func PasswordCiphertextNotIn(vs ...[]byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldPasswordCiphertext, vs...))
}

// PasswordCiphertextGT applies the GT predicate on the "password_ciphertext" field.
func PasswordCiphertextGT(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldPasswordCiphertext, v))
}

// PasswordCiphertextGTE applies the GTE predicate on the "password_ciphertext" field.
func PasswordCiphertextGTE(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldPasswordCiphertext, v))
}

// PasswordCiphertextLT applies the LT predicate on the "password_ciphertext" field.
func PasswordCiphertextLT(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldPasswordCiphertext, v))
}

// PasswordCiphertextLTE applies the LTE predicate on the "password_ciphertext" field.
func PasswordCiphertextLTE(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldPasswordCiphertext, v))
}

// PasswordCiphertextIsNil applies the IsNil predicate on the "password_ciphertext" field.
func PasswordCiphertextIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldPasswordCiphertext))
}

// PasswordCiphertextNotNil applies the NotNil predicate on the "password_ciphertext" field.
func PasswordCiphertextNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldPasswordCiphertext))
}

// PasswordKeyIDEQ applies the EQ predicate on the "password_key_id" field.
func PasswordKeyIDEQ(v uint8) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldPasswordKeyID, v))
}

// PasswordKeyIDNEQ applies the NEQ predicate on the "password_key_id" field.
func PasswordKeyIDNEQ(v uint8) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldPasswordKeyID, v))
}

// PasswordKeyIDIn applies the In predicate on the "password_key_id" field.
func PasswordKeyIDIn(vs ...uint8) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldPasswordKeyID, vs...))
}

// PasswordKeyIDNotIn applies the NotIn predicate on the "password_key_id" field.
func PasswordKeyIDNotIn(vs ...uint8) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldPasswordKeyID, vs...))
}

// PasswordKeyIDGT applies the GT predicate on the "password_key_id" field.
func PasswordKeyIDGT(v uint8) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldPasswordKeyID, v))
}

// PasswordKeyIDGTE applies the GTE predicate on the "password_key_id" field.
func PasswordKeyIDGTE(v uint8) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldPasswordKeyID, v))
}

// PasswordKeyIDLT applies the LT predicate on the "password_key_id" field.
func PasswordKeyIDLT(v uint8) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldPasswordKeyID, v))
}

// PasswordKeyIDLTE applies the LTE predicate on the "password_key_id" field.
func PasswordKeyIDLTE(v uint8) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldPasswordKeyID, v))
}

// PasswordKeyIDIsNil applies the IsNil predicate on the "password_key_id" field.
func PasswordKeyIDIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldPasswordKeyID))
}

// PasswordKeyIDNotNil applies the NotNil predicate on the "password_key_id" field.
func PasswordKeyIDNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldPasswordKeyID))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "public_key" field.
func PublicKeyContains(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "public_key" field.
func PublicKeyHasPrefix(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "public_key" field.
func PublicKeyHasSuffix(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyIsNil applies the IsNil predicate on the "public_key" field.
func PublicKeyIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldPublicKey))
}

// PublicKeyNotNil applies the NotNil predicate on the "public_key" field.
func PublicKeyNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldPublicKey))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "public_key" field.
func PublicKeyEqualFold(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "public_key" field.
func PublicKeyContainsFold(v string) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldContainsFold(FieldPublicKey, v))
}

// PrivateKeyCiphertextEQ applies the EQ predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextEQ(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextNEQ applies the NEQ predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextNEQ(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextIn applies the In predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextIn(vs ...[]byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldPrivateKeyCiphertext, vs...))
}

// PrivateKeyCiphertextNotIn applies the NotIn predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextNotIn(vs ...[]byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldPrivateKeyCiphertext, vs...))
}

// PrivateKeyCiphertextGT applies the GT predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextGT(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextGTE applies the GTE predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextGTE(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextLT applies the LT predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextLT(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextLTE applies the LTE predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextLTE(v []byte) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextIsNil applies the IsNil predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldPrivateKeyCiphertext))
}

// PrivateKeyCiphertextNotNil applies the NotNil predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldPrivateKeyCiphertext))
}

// CaCertsIsNil applies the IsNil predicate on the "ca_certs" field.
func CaCertsIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldCaCerts))
}

// CaCertsNotNil applies the NotNil predicate on the "ca_certs" field.
func CaCertsNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldCaCerts))
}

// AllowedDevicesIsNil applies the IsNil predicate on the "allowed_devices" field.
func AllowedDevicesIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldAllowedDevices))
}

// AllowedDevicesNotNil applies the NotNil predicate on the "allowed_devices" field.
func AllowedDevicesNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldAllowedDevices))
}

// GroupsIsNil applies the IsNil predicate on the "groups" field.
func GroupsIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldGroups))
}

// GroupsNotNil applies the NotNil predicate on the "groups" field.
func GroupsNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldGroups))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldStatus, vs...))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldMetadata))
}

// FirstConnectionAtEQ applies the EQ predicate on the "first_connection_at" field.
func FirstConnectionAtEQ(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldFirstConnectionAt, v))
}

// FirstConnectionAtNEQ applies the NEQ predicate on the "first_connection_at" field.
func FirstConnectionAtNEQ(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldFirstConnectionAt, v))
}

// FirstConnectionAtIn applies the In predicate on the "first_connection_at" field.
func FirstConnectionAtIn(vs ...time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldFirstConnectionAt, vs...))
}

// FirstConnectionAtNotIn applies the NotIn predicate on the "first_connection_at" field.
func FirstConnectionAtNotIn(vs ...time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldFirstConnectionAt, vs...))
}

// FirstConnectionAtGT applies the GT predicate on the "first_connection_at" field.
func FirstConnectionAtGT(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldFirstConnectionAt, v))
}

// FirstConnectionAtGTE applies the GTE predicate on the "first_connection_at" field.
func FirstConnectionAtGTE(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldFirstConnectionAt, v))
}

// FirstConnectionAtLT applies the LT predicate on the "first_connection_at" field.
func FirstConnectionAtLT(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldFirstConnectionAt, v))
}

// FirstConnectionAtLTE applies the LTE predicate on the "first_connection_at" field.
func FirstConnectionAtLTE(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldFirstConnectionAt, v))
}

// FirstConnectionAtIsNil applies the IsNil predicate on the "first_connection_at" field.
func FirstConnectionAtIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldFirstConnectionAt))
}

// FirstConnectionAtNotNil applies the NotNil predicate on the "first_connection_at" field.
func FirstConnectionAtNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldFirstConnectionAt))
}

// LastConnectionAtEQ applies the EQ predicate on the "last_connection_at" field.
func LastConnectionAtEQ(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldLastConnectionAt, v))
}

// LastConnectionAtNEQ applies the NEQ predicate on the "last_connection_at" field.
func LastConnectionAtNEQ(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldLastConnectionAt, v))
}

// LastConnectionAtIn applies the In predicate on the "last_connection_at" field.
func LastConnectionAtIn(vs ...time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldLastConnectionAt, vs...))
}

// LastConnectionAtNotIn applies the NotIn predicate on the "last_connection_at" field.
func LastConnectionAtNotIn(vs ...time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldLastConnectionAt, vs...))
}

// LastConnectionAtGT applies the GT predicate on the "last_connection_at" field.
func LastConnectionAtGT(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGT(FieldLastConnectionAt, v))
}

// LastConnectionAtGTE applies the GTE predicate on the "last_connection_at" field.
func LastConnectionAtGTE(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldGTE(FieldLastConnectionAt, v))
}

// LastConnectionAtLT applies the LT predicate on the "last_connection_at" field.
func LastConnectionAtLT(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLT(FieldLastConnectionAt, v))
}

// LastConnectionAtLTE applies the LTE predicate on the "last_connection_at" field.
func LastConnectionAtLTE(v time.Time) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldLTE(FieldLastConnectionAt, v))
}

// LastConnectionAtIsNil applies the IsNil predicate on the "last_connection_at" field.
func LastConnectionAtIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldLastConnectionAt))
}

// LastConnectionAtNotNil applies the NotNil predicate on the "last_connection_at" field.
func LastConnectionAtNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldLastConnectionAt))
}

// ResellerIDEQ applies the EQ predicate on the "reseller_id" field.
func ResellerIDEQ(v uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldResellerID, v))
}

// ResellerIDNEQ applies the NEQ predicate on the "reseller_id" field.
func ResellerIDNEQ(v uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldResellerID, v))
}

// ResellerIDIn applies the In predicate on the "reseller_id" field.
func ResellerIDIn(vs ...uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldResellerID, vs...))
}

// ResellerIDNotIn applies the NotIn predicate on the "reseller_id" field.
func ResellerIDNotIn(vs ...uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldResellerID, vs...))
}

// ResellerIDIsNil applies the IsNil predicate on the "reseller_id" field.
func ResellerIDIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldResellerID))
}

// ResellerIDNotNil applies the NotNil predicate on the "reseller_id" field.
func ResellerIDNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldResellerID))
}

// ActivePlanIDEQ applies the EQ predicate on the "active_plan_id" field.
func ActivePlanIDEQ(v uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldEQ(FieldActivePlanID, v))
}

// ActivePlanIDNEQ applies the NEQ predicate on the "active_plan_id" field.
func ActivePlanIDNEQ(v uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNEQ(FieldActivePlanID, v))
}

// ActivePlanIDIn applies the In predicate on the "active_plan_id" field.
func ActivePlanIDIn(vs ...uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIn(FieldActivePlanID, vs...))
}

// ActivePlanIDNotIn applies the NotIn predicate on the "active_plan_id" field.
func ActivePlanIDNotIn(vs ...uuid.UUID) predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotIn(FieldActivePlanID, vs...))
}

// ActivePlanIDIsNil applies the IsNil predicate on the "active_plan_id" field.
func ActivePlanIDIsNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldIsNull(FieldActivePlanID))
}

// ActivePlanIDNotNil applies the NotNil predicate on the "active_plan_id" field.
func ActivePlanIDNotNil() predicate.Subscriber {
	return predicate.Subscriber(sql.FieldNotNull(FieldActivePlanID))
}

// HasReseller applies the HasEdge predicate on the "reseller" edge.
func HasReseller() predicate.Subscriber {
	return predicate.Subscriber(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ResellerTable, ResellerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResellerWith applies the HasEdge predicate on the "reseller" edge with a given conditions (other predicates).
func HasResellerWith(preds ...predicate.Reseller) predicate.Subscriber {
	return predicate.Subscriber(func(s *sql.Selector) {
		step := newResellerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsagePlans applies the HasEdge predicate on the "usage_plans" edge.
func HasUsagePlans() predicate.Subscriber {
	return predicate.Subscriber(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsagePlansTable, UsagePlansColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsagePlansWith applies the HasEdge predicate on the "usage_plans" edge with a given conditions (other predicates).
func HasUsagePlansWith(preds ...predicate.UsagePlan) predicate.Subscriber {
	return predicate.Subscriber(func(s *sql.Selector) {
		step := newUsagePlansStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActivePlan applies the HasEdge predicate on the "active_plan" edge.
func HasActivePlan() predicate.Subscriber {
	return predicate.Subscriber(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ActivePlanTable, ActivePlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActivePlanWith applies the HasEdge predicate on the "active_plan" edge with a given conditions (other predicates).
func HasActivePlanWith(preds ...predicate.UsagePlan) predicate.Subscriber {
	return predicate.Subscriber(func(s *sql.Selector) {
		step := newActivePlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscriber) predicate.Subscriber {
	return predicate.Subscriber(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscriber) predicate.Subscriber {
	return predicate.Subscriber(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscriber) predicate.Subscriber {
	return predicate.Subscriber(sql.NotPredicates(p))
}
