// Code generated by ent, DO NOT EDIT.

package node

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIps holds the string denoting the ips field in the database.
	FieldIps = "ips"
	// FieldAllowedCidrs holds the string denoting the allowed_cidrs field in the database.
	FieldAllowedCidrs = "allowed_cidrs"
	// FieldTrafficMultiplier holds the string denoting the traffic_multiplier field in the database.
	FieldTrafficMultiplier = "traffic_multiplier"
	// FieldResetMode holds the string denoting the reset_mode field in the database.
	FieldResetMode = "reset_mode"
	// FieldResetAnchor holds the string denoting the reset_anchor field in the database.
	FieldResetAnchor = "reset_anchor"
	// FieldCurrentTotal holds the string denoting the current_total field in the database.
	FieldCurrentTotal = "current_total"
	// FieldCurrentUpload holds the string denoting the current_upload field in the database.
	FieldCurrentUpload = "current_upload"
	// FieldCurrentDownload holds the string denoting the current_download field in the database.
	FieldCurrentDownload = "current_download"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldIsp holds the string denoting the isp field in the database.
	FieldIsp = "isp"
	// FieldAsn holds the string denoting the asn field in the database.
	FieldAsn = "asn"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeServices holds the string denoting the services edge name in mutations.
	EdgeServices = "services"
	// Table holds the table name of the node in the database.
	Table = "nodes"
	// ServicesTable is the table that holds the services relation/edge.
	ServicesTable = "services"
	// ServicesInverseTable is the table name for the Service entity.
	// It exists in this package in order to avoid circular dependency with the "service" package.
	ServicesInverseTable = "services"
	// ServicesColumn is the table column denoting the services relation/edge.
	ServicesColumn = "node_id"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldIps,
	FieldAllowedCidrs,
	FieldTrafficMultiplier,
	FieldResetMode,
	FieldResetAnchor,
	FieldCurrentTotal,
	FieldCurrentUpload,
	FieldCurrentDownload,
	FieldCountry,
	FieldCity,
	FieldIsp,
	FieldAsn,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultTrafficMultiplier holds the default value on creation for the "traffic_multiplier" field.
	DefaultTrafficMultiplier float64
	// DefaultCurrentTotal holds the default value on creation for the "current_total" field.
	DefaultCurrentTotal int64
	// CurrentTotalValidator is a validator for the "current_total" field. It is called by the builders before save.
	CurrentTotalValidator func(int64) error
	// DefaultCurrentUpload holds the default value on creation for the "current_upload" field.
	DefaultCurrentUpload int64
	// CurrentUploadValidator is a validator for the "current_upload" field. It is called by the builders before save.
	CurrentUploadValidator func(int64) error
	// DefaultCurrentDownload holds the default value on creation for the "current_download" field.
	DefaultCurrentDownload int64
	// CurrentDownloadValidator is a validator for the "current_download" field. It is called by the builders before save.
	CurrentDownloadValidator func(int64) error
	// CountryValidator is a validator for the "country" field. It is called by the builders before save.
	CountryValidator func(string) error
	// CityValidator is a validator for the "city" field. It is called by the builders before save.
	CityValidator func(string) error
	// IspValidator is a validator for the "isp" field. It is called by the builders before save.
	IspValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ResetMode defines the type for the "reset_mode" enum field.
type ResetMode string

// ResetModeNoReset is the default value of the ResetMode enum.
const DefaultResetMode = ResetModeNoReset

// ResetMode values.
const (
	ResetModeNoReset ResetMode = "no_reset"
	ResetModeHourly  ResetMode = "hourly"
	ResetModeDaily   ResetMode = "daily"
	ResetModeWeekly  ResetMode = "weekly"
	ResetModeMonthly ResetMode = "monthly"
	ResetModeYearly  ResetMode = "yearly"
)

func (rm ResetMode) String() string {
	return string(rm)
}

// ResetModeValidator is a validator for the "reset_mode" field enum values. It is called by the builders before save.
func ResetModeValidator(rm ResetMode) error {
	switch rm {
	case ResetModeNoReset, ResetModeHourly, ResetModeDaily, ResetModeWeekly, ResetModeMonthly, ResetModeYearly:
		return nil
	default:
		return fmt.Errorf("node: invalid enum value for reset_mode field: %q", rm)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("node: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Node queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTrafficMultiplier orders the results by the traffic_multiplier field.
func ByTrafficMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrafficMultiplier, opts...).ToFunc()
}

// ByResetMode orders the results by the reset_mode field.
func ByResetMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetMode, opts...).ToFunc()
}

// ByResetAnchor orders the results by the reset_anchor field.
func ByResetAnchor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetAnchor, opts...).ToFunc()
}

// ByCurrentTotal orders the results by the current_total field.
func ByCurrentTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentTotal, opts...).ToFunc()
}

// ByCurrentUpload orders the results by the current_upload field.
func ByCurrentUpload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentUpload, opts...).ToFunc()
}

// ByCurrentDownload orders the results by the current_download field.
func ByCurrentDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentDownload, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByIsp orders the results by the isp field.
func ByIsp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsp, opts...).ToFunc()
}

// ByAsn orders the results by the asn field.
func ByAsn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAsn, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByServicesCount orders the results by services count.
func ByServicesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newServicesStep(), opts...)
	}
}

// ByServices orders the results by services terms.
func ByServices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServicesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newServicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ServicesTable, ServicesColumn),
	)
}
