// Code generated by ent, DO NOT EDIT.

package node

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/hiddify/hue/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldName, v))
}

// TrafficMultiplier applies equality check predicate on the "traffic_multiplier" field. It's identical to TrafficMultiplierEQ.
func TrafficMultiplier(v float64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldTrafficMultiplier, v))
}

// ResetAnchor applies equality check predicate on the "reset_anchor" field. It's identical to ResetAnchorEQ.
func ResetAnchor(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldResetAnchor, v))
}

// CurrentTotal applies equality check predicate on the "current_total" field. It's identical to CurrentTotalEQ.
func CurrentTotal(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCurrentTotal, v))
}

// CurrentUpload applies equality check predicate on the "current_upload" field. It's identical to CurrentUploadEQ.
func CurrentUpload(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCurrentUpload, v))
}

// CurrentDownload applies equality check predicate on the "current_download" field. It's identical to CurrentDownloadEQ.
func CurrentDownload(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCurrentDownload, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCountry, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCity, v))
}

// Isp applies equality check predicate on the "isp" field. It's identical to IspEQ.
func Isp(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldIsp, v))
}

// Asn applies equality check predicate on the "asn" field. It's identical to AsnEQ.
func Asn(v uint32) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldAsn, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldName, v))
}

// IpsIsNil applies the IsNil predicate on the "ips" field.
func IpsIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldIps))
}

// IpsNotNil applies the NotNil predicate on the "ips" field.
func IpsNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldIps))
}

// AllowedCidrsIsNil applies the IsNil predicate on the "allowed_cidrs" field.
func AllowedCidrsIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldAllowedCidrs))
}

// AllowedCidrsNotNil applies the NotNil predicate on the "allowed_cidrs" field.
func AllowedCidrsNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldAllowedCidrs))
}

// TrafficMultiplierEQ applies the EQ predicate on the "traffic_multiplier" field.
func TrafficMultiplierEQ(v float64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldTrafficMultiplier, v))
}

// TrafficMultiplierNEQ applies the NEQ predicate on the "traffic_multiplier" field.
func TrafficMultiplierNEQ(v float64) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldTrafficMultiplier, v))
}

// TrafficMultiplierIn applies the In predicate on the "traffic_multiplier" field.
func TrafficMultiplierIn(vs ...float64) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldTrafficMultiplier, vs...))
}

// TrafficMultiplierNotIn applies the NotIn predicate on the "traffic_multiplier" field.
func TrafficMultiplierNotIn(vs ...float64) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldTrafficMultiplier, vs...))
}

// TrafficMultiplierGT applies the GT predicate on the "traffic_multiplier" field.
func TrafficMultiplierGT(v float64) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldTrafficMultiplier, v))
}

// TrafficMultiplierGTE applies the GTE predicate on the "traffic_multiplier" field.
func TrafficMultiplierGTE(v float64) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldTrafficMultiplier, v))
}

// TrafficMultiplierLT applies the LT predicate on the "traffic_multiplier" field.
func TrafficMultiplierLT(v float64) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldTrafficMultiplier, v))
}

// TrafficMultiplierLTE applies the LTE predicate on the "traffic_multiplier" field.
func TrafficMultiplierLTE(v float64) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldTrafficMultiplier, v))
}

// ResetModeEQ applies the EQ predicate on the "reset_mode" field.
func ResetModeEQ(v ResetMode) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldResetMode, v))
}

// ResetModeNEQ applies the NEQ predicate on the "reset_mode" field.
func ResetModeNEQ(v ResetMode) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldResetMode, v))
}

// ResetModeIn applies the In predicate on the "reset_mode" field.
func ResetModeIn(vs ...ResetMode) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldResetMode, vs...))
}

// ResetModeNotIn applies the NotIn predicate on the "reset_mode" field.
func ResetModeNotIn(vs ...ResetMode) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldResetMode, vs...))
}

// ResetAnchorEQ applies the EQ predicate on the "reset_anchor" field.
func ResetAnchorEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldResetAnchor, v))
}

// ResetAnchorNEQ applies the NEQ predicate on the "reset_anchor" field.
func ResetAnchorNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldResetAnchor, v))
}

// ResetAnchorIn applies the In predicate on the "reset_anchor" field.
func ResetAnchorIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldResetAnchor, vs...))
}

// ResetAnchorNotIn applies the NotIn predicate on the "reset_anchor" field.
func ResetAnchorNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldResetAnchor, vs...))
}

// ResetAnchorGT applies the GT predicate on the "reset_anchor" field.
func ResetAnchorGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldResetAnchor, v))
}

// ResetAnchorGTE applies the GTE predicate on the "reset_anchor" field.
func ResetAnchorGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldResetAnchor, v))
}

// ResetAnchorLT applies the LT predicate on the "reset_anchor" field.
func ResetAnchorLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldResetAnchor, v))
}

// ResetAnchorLTE applies the LTE predicate on the "reset_anchor" field.
func ResetAnchorLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldResetAnchor, v))
}

// ResetAnchorIsNil applies the IsNil predicate on the "reset_anchor" field.
func ResetAnchorIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldResetAnchor))
}

// ResetAnchorNotNil applies the NotNil predicate on the "reset_anchor" field.
func ResetAnchorNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldResetAnchor))
}

// CurrentTotalEQ applies the EQ predicate on the "current_total" field.
func CurrentTotalEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCurrentTotal, v))
}

// CurrentTotalNEQ applies the NEQ predicate on the "current_total" field.
func CurrentTotalNEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCurrentTotal, v))
}

// CurrentTotalIn applies the In predicate on the "current_total" field.
func CurrentTotalIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCurrentTotal, vs...))
}

// CurrentTotalNotIn applies the NotIn predicate on the "current_total" field.
func CurrentTotalNotIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCurrentTotal, vs...))
}

// CurrentTotalGT applies the GT predicate on the "current_total" field.
func CurrentTotalGT(v int64) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCurrentTotal, v))
}

// CurrentTotalGTE applies the GTE predicate on the "current_total" field.
func CurrentTotalGTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCurrentTotal, v))
}

// CurrentTotalLT applies the LT predicate on the "current_total" field.
func CurrentTotalLT(v int64) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCurrentTotal, v))
}

// CurrentTotalLTE applies the LTE predicate on the "current_total" field.
func CurrentTotalLTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCurrentTotal, v))
}

// CurrentUploadEQ applies the EQ predicate on the "current_upload" field.
func CurrentUploadEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCurrentUpload, v))
}

// CurrentUploadNEQ applies the NEQ predicate on the "current_upload" field.
func CurrentUploadNEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCurrentUpload, v))
}

// CurrentUploadIn applies the In predicate on the "current_upload" field.
func CurrentUploadIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCurrentUpload, vs...))
}

// CurrentUploadNotIn applies the NotIn predicate on the "current_upload" field.
func CurrentUploadNotIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCurrentUpload, vs...))
}

// CurrentUploadGT applies the GT predicate on the "current_upload" field.
func CurrentUploadGT(v int64) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCurrentUpload, v))
}

// CurrentUploadGTE applies the GTE predicate on the "current_upload" field.
func CurrentUploadGTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCurrentUpload, v))
}

// CurrentUploadLT applies the LT predicate on the "current_upload" field.
func CurrentUploadLT(v int64) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCurrentUpload, v))
}

// CurrentUploadLTE applies the LTE predicate on the "current_upload" field.
func CurrentUploadLTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCurrentUpload, v))
}

// CurrentDownloadEQ applies the EQ predicate on the "current_download" field.
func CurrentDownloadEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCurrentDownload, v))
}

// CurrentDownloadNEQ applies the NEQ predicate on the "current_download" field.
func CurrentDownloadNEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCurrentDownload, v))
}

// CurrentDownloadIn applies the In predicate on the "current_download" field.
func CurrentDownloadIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCurrentDownload, vs...))
}

// CurrentDownloadNotIn applies the NotIn predicate on the "current_download" field.
func CurrentDownloadNotIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCurrentDownload, vs...))
}

// CurrentDownloadGT applies the GT predicate on the "current_download" field.
func CurrentDownloadGT(v int64) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCurrentDownload, v))
}

// CurrentDownloadGTE applies the GTE predicate on the "current_download" field.
func CurrentDownloadGTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCurrentDownload, v))
}

// CurrentDownloadLT applies the LT predicate on the "current_download" field.
func CurrentDownloadLT(v int64) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCurrentDownload, v))
}

// CurrentDownloadLTE applies the LTE predicate on the "current_download" field.
func CurrentDownloadLTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCurrentDownload, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryIsNil applies the IsNil predicate on the "country" field.
func CountryIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldCountry))
}

// CountryNotNil applies the NotNil predicate on the "country" field.
func CountryNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldCountry))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldCountry, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldCity, v))
}

// CityIsNil applies the IsNil predicate on the "city" field.
func CityIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldCity))
}

// CityNotNil applies the NotNil predicate on the "city" field.
func CityNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldCity))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldCity, v))
}

// IspEQ applies the EQ predicate on the "isp" field.
func IspEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldIsp, v))
}

// IspNEQ applies the NEQ predicate on the "isp" field.
func IspNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldIsp, v))
}

// IspIn applies the In predicate on the "isp" field.
func IspIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldIsp, vs...))
}

// IspNotIn applies the NotIn predicate on the "isp" field.
func IspNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldIsp, vs...))
}

// IspGT applies the GT predicate on the "isp" field.
func IspGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldIsp, v))
}

// IspGTE applies the GTE predicate on the "isp" field.
func IspGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldIsp, v))
}

// IspLT applies the LT predicate on the "isp" field.
func IspLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldIsp, v))
}

// IspLTE applies the LTE predicate on the "isp" field.
func IspLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldIsp, v))
}

// IspContains applies the Contains predicate on the "isp" field.
func IspContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldIsp, v))
}

// IspHasPrefix applies the HasPrefix predicate on the "isp" field.
func IspHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldIsp, v))
}

// IspHasSuffix applies the HasSuffix predicate on the "isp" field.
func IspHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldIsp, v))
}

// IspIsNil applies the IsNil predicate on the "isp" field.
func IspIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldIsp))
}

// IspNotNil applies the NotNil predicate on the "isp" field.
func IspNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldIsp))
}

// IspEqualFold applies the EqualFold predicate on the "isp" field.
func IspEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldIsp, v))
}

// IspContainsFold applies the ContainsFold predicate on the "isp" field.
func IspContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldIsp, v))
}

// AsnEQ applies the EQ predicate on the "asn" field.
func AsnEQ(v uint32) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldAsn, v))
}

// AsnNEQ applies the NEQ predicate on the "asn" field.
func AsnNEQ(v uint32) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldAsn, v))
}

// AsnIn applies the In predicate on the "asn" field.
func AsnIn(vs ...uint32) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldAsn, vs...))
}

// AsnNotIn applies the NotIn predicate on the "asn" field.
func AsnNotIn(vs ...uint32) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldAsn, vs...))
}

// AsnGT applies the GT predicate on the "asn" field.
func AsnGT(v uint32) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldAsn, v))
}

// AsnGTE applies the GTE predicate on the "asn" field.
func AsnGTE(v uint32) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldAsn, v))
}

// AsnLT applies the LT predicate on the "asn" field.
func AsnLT(v uint32) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldAsn, v))
}

// AsnLTE applies the LTE predicate on the "asn" field.
func AsnLTE(v uint32) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldAsn, v))
}

// AsnIsNil applies the IsNil predicate on the "asn" field.
func AsnIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldAsn))
}

// AsnNotNil applies the NotNil predicate on the "asn" field.
func AsnNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldAsn))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldStatus, vs...))
}

// HasServices applies the HasEdge predicate on the "services" edge.
func HasServices() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ServicesTable, ServicesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServicesWith applies the HasEdge predicate on the "services" edge with a given conditions (other predicates).
func HasServicesWith(preds ...predicate.Service) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newServicesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Node) predicate.Node {
	return predicate.Node(sql.NotPredicates(p))
}
