// Code generated by ent, DO NOT EDIT.

package domaincertificate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hiddify/hue/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicKeyPem applies equality check predicate on the "public_key_pem" field. It's identical to PublicKeyPemEQ.
func PublicKeyPem(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldPublicKeyPem, v))
}

// PrivateKeyCiphertext applies equality check predicate on the "private_key_ciphertext" field. It's identical to PrivateKeyCiphertextEQ.
func PrivateKeyCiphertext(v []byte) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyKeyID applies equality check predicate on the "private_key_key_id" field. It's identical to PrivateKeyKeyIDEQ.
func PrivateKeyKeyID(v uint8) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldPrivateKeyKeyID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldExpiresAt, v))
}

// GeneratedNodeID applies equality check predicate on the "generated_node_id" field. It's identical to GeneratedNodeIDEQ.
func GeneratedNodeID(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldGeneratedNodeID, v))
}

// Valid applies equality check predicate on the "valid" field. It's identical to ValidEQ.
func Valid(v bool) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldValid, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLTE(FieldUpdatedAt, v))
}

// PublicKeyPemEQ applies the EQ predicate on the "public_key_pem" field.
func PublicKeyPemEQ(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldPublicKeyPem, v))
}

// PublicKeyPemNEQ applies the NEQ predicate on the "public_key_pem" field.
func PublicKeyPemNEQ(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldPublicKeyPem, v))
}

// PublicKeyPemIn applies the In predicate on the "public_key_pem" field.
func PublicKeyPemIn(vs ...string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIn(FieldPublicKeyPem, vs...))
}

// PublicKeyPemNotIn applies the NotIn predicate on the "public_key_pem" field.
func PublicKeyPemNotIn(vs ...string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotIn(FieldPublicKeyPem, vs...))
}

// PublicKeyPemGT applies the GT predicate on the "public_key_pem" field.
func PublicKeyPemGT(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGT(FieldPublicKeyPem, v))
}

// PublicKeyPemGTE applies the GTE predicate on the "public_key_pem" field.
func PublicKeyPemGTE(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGTE(FieldPublicKeyPem, v))
}

// PublicKeyPemLT applies the LT predicate on the "public_key_pem" field.
func PublicKeyPemLT(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLT(FieldPublicKeyPem, v))
}

// PublicKeyPemLTE applies the LTE predicate on the "public_key_pem" field.
func PublicKeyPemLTE(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLTE(FieldPublicKeyPem, v))
}

// PublicKeyPemContains applies the Contains predicate on the "public_key_pem" field.
func PublicKeyPemContains(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldContains(FieldPublicKeyPem, v))
}

// PublicKeyPemHasPrefix applies the HasPrefix predicate on the "public_key_pem" field.
func PublicKeyPemHasPrefix(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldHasPrefix(FieldPublicKeyPem, v))
}

// PublicKeyPemHasSuffix applies the HasSuffix predicate on the "public_key_pem" field.
func PublicKeyPemHasSuffix(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldHasSuffix(FieldPublicKeyPem, v))
}

// PublicKeyPemEqualFold applies the EqualFold predicate on the "public_key_pem" field.
func PublicKeyPemEqualFold(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEqualFold(FieldPublicKeyPem, v))
}

// PublicKeyPemContainsFold applies the ContainsFold predicate on the "public_key_pem" field.
func PublicKeyPemContainsFold(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldContainsFold(FieldPublicKeyPem, v))
}

// PrivateKeyCiphertextEQ applies the EQ predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextEQ(v []byte) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextNEQ applies the NEQ predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextNEQ(v []byte) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextIn applies the In predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextIn(vs ...[]byte) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIn(FieldPrivateKeyCiphertext, vs...))
}

// PrivateKeyCiphertextNotIn applies the NotIn predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextNotIn(vs ...[]byte) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotIn(FieldPrivateKeyCiphertext, vs...))
}

// PrivateKeyCiphertextGT applies the GT predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextGT(v []byte) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGT(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextGTE applies the GTE predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextGTE(v []byte) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGTE(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextLT applies the LT predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextLT(v []byte) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLT(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyCiphertextLTE applies the LTE predicate on the "private_key_ciphertext" field.
func PrivateKeyCiphertextLTE(v []byte) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLTE(FieldPrivateKeyCiphertext, v))
}

// PrivateKeyKeyIDEQ applies the EQ predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDEQ(v uint8) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldPrivateKeyKeyID, v))
}

// PrivateKeyKeyIDNEQ applies the NEQ predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDNEQ(v uint8) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldPrivateKeyKeyID, v))
}

// PrivateKeyKeyIDIn applies the In predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDIn(vs ...uint8) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIn(FieldPrivateKeyKeyID, vs...))
}

// PrivateKeyKeyIDNotIn applies the NotIn predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDNotIn(vs ...uint8) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotIn(FieldPrivateKeyKeyID, vs...))
}

// PrivateKeyKeyIDGT applies the GT predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDGT(v uint8) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGT(FieldPrivateKeyKeyID, v))
}

// PrivateKeyKeyIDGTE applies the GTE predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDGTE(v uint8) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGTE(FieldPrivateKeyKeyID, v))
}

// PrivateKeyKeyIDLT applies the LT predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDLT(v uint8) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLT(FieldPrivateKeyKeyID, v))
}

// PrivateKeyKeyIDLTE applies the LTE predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDLTE(v uint8) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLTE(FieldPrivateKeyKeyID, v))
}

// PrivateKeyKeyIDIsNil applies the IsNil predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDIsNil() predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIsNull(FieldPrivateKeyKeyID))
}

// PrivateKeyKeyIDNotNil applies the NotNil predicate on the "private_key_key_id" field.
func PrivateKeyKeyIDNotNil() predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotNull(FieldPrivateKeyKeyID))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLTE(FieldExpiresAt, v))
}

// IssuerEQ applies the EQ predicate on the "issuer" field.
func IssuerEQ(v Issuer) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldIssuer, v))
}

// IssuerNEQ applies the NEQ predicate on the "issuer" field.
func IssuerNEQ(v Issuer) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldIssuer, v))
}

// IssuerIn applies the In predicate on the "issuer" field.
func IssuerIn(vs ...Issuer) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIn(FieldIssuer, vs...))
}

// IssuerNotIn applies the NotIn predicate on the "issuer" field.
func IssuerNotIn(vs ...Issuer) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotIn(FieldIssuer, vs...))
}

// GeneratedNodeIDEQ applies the EQ predicate on the "generated_node_id" field.
func GeneratedNodeIDEQ(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDNEQ applies the NEQ predicate on the "generated_node_id" field.
func GeneratedNodeIDNEQ(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDIn applies the In predicate on the "generated_node_id" field.
func GeneratedNodeIDIn(vs ...string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIn(FieldGeneratedNodeID, vs...))
}

// GeneratedNodeIDNotIn applies the NotIn predicate on the "generated_node_id" field.
func GeneratedNodeIDNotIn(vs ...string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotIn(FieldGeneratedNodeID, vs...))
}

// GeneratedNodeIDGT applies the GT predicate on the "generated_node_id" field.
func GeneratedNodeIDGT(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGT(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDGTE applies the GTE predicate on the "generated_node_id" field.
func GeneratedNodeIDGTE(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldGTE(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDLT applies the LT predicate on the "generated_node_id" field.
func GeneratedNodeIDLT(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLT(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDLTE applies the LTE predicate on the "generated_node_id" field.
func GeneratedNodeIDLTE(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldLTE(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDContains applies the Contains predicate on the "generated_node_id" field.
func GeneratedNodeIDContains(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldContains(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDHasPrefix applies the HasPrefix predicate on the "generated_node_id" field.
func GeneratedNodeIDHasPrefix(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldHasPrefix(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDHasSuffix applies the HasSuffix predicate on the "generated_node_id" field.
func GeneratedNodeIDHasSuffix(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldHasSuffix(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDIsNil applies the IsNil predicate on the "generated_node_id" field.
func GeneratedNodeIDIsNil() predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldIsNull(FieldGeneratedNodeID))
}

// GeneratedNodeIDNotNil applies the NotNil predicate on the "generated_node_id" field.
func GeneratedNodeIDNotNil() predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNotNull(FieldGeneratedNodeID))
}

// GeneratedNodeIDEqualFold applies the EqualFold predicate on the "generated_node_id" field.
func GeneratedNodeIDEqualFold(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEqualFold(FieldGeneratedNodeID, v))
}

// GeneratedNodeIDContainsFold applies the ContainsFold predicate on the "generated_node_id" field.
func GeneratedNodeIDContainsFold(v string) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldContainsFold(FieldGeneratedNodeID, v))
}

// ValidEQ applies the EQ predicate on the "valid" field.
func ValidEQ(v bool) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldEQ(FieldValid, v))
}

// ValidNEQ applies the NEQ predicate on the "valid" field.
func ValidNEQ(v bool) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.FieldNEQ(FieldValid, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DomainCertificate) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DomainCertificate) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DomainCertificate) predicate.DomainCertificate {
	return predicate.DomainCertificate(sql.NotPredicates(p))
}
