// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/hiddify/hue/internal/ent"
	"github.com/hiddify/hue/internal/ent/agent"
	"github.com/hiddify/hue/internal/ent/apikey"
	"github.com/hiddify/hue/internal/ent/domaincertificate"
	"github.com/hiddify/hue/internal/ent/event"
	"github.com/hiddify/hue/internal/ent/node"
	"github.com/hiddify/hue/internal/ent/predicate"
	"github.com/hiddify/hue/internal/ent/refreshtoken"
	"github.com/hiddify/hue/internal/ent/reseller"
	"github.com/hiddify/hue/internal/ent/resellerplan"
	"github.com/hiddify/hue/internal/ent/signingkey"
	"github.com/hiddify/hue/internal/ent/subscriber"
	"github.com/hiddify/hue/internal/ent/usageplan"
	"github.com/hiddify/hue/internal/ent/usagereport"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The AgentFunc type is an adapter to allow the use of ordinary function as a Querier.
type AgentFunc func(context.Context, *ent.AgentQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AgentFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AgentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AgentQuery", q)
}

// The TraverseAgent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAgent func(context.Context, *ent.AgentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAgent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAgent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AgentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AgentQuery", q)
}

// The ApiKeyFunc type is an adapter to allow the use of ordinary function as a Querier.
type ApiKeyFunc func(context.Context, *ent.ApiKeyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ApiKeyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ApiKeyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ApiKeyQuery", q)
}

// The TraverseApiKey type is an adapter to allow the use of ordinary function as Traverser.
type TraverseApiKey func(context.Context, *ent.ApiKeyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseApiKey) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseApiKey) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ApiKeyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ApiKeyQuery", q)
}

// The DomainCertificateFunc type is an adapter to allow the use of ordinary function as a Querier.
type DomainCertificateFunc func(context.Context, *ent.DomainCertificateQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f DomainCertificateFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.DomainCertificateQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DomainCertificateQuery", q)
}

// The TraverseDomainCertificate type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDomainCertificate func(context.Context, *ent.DomainCertificateQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDomainCertificate) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDomainCertificate) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.DomainCertificateQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DomainCertificateQuery", q)
}

// The EventFunc type is an adapter to allow the use of ordinary function as a Querier.
type EventFunc func(context.Context, *ent.EventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f EventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.EventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.EventQuery", q)
}

// The TraverseEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseEvent func(context.Context, *ent.EventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.EventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.EventQuery", q)
}

// The NodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type NodeFunc func(context.Context, *ent.NodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f NodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.NodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.NodeQuery", q)
}

// The TraverseNode type is an adapter to allow the use of ordinary function as Traverser.
type TraverseNode func(context.Context, *ent.NodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseNode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseNode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.NodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.NodeQuery", q)
}

// The RefreshTokenFunc type is an adapter to allow the use of ordinary function as a Querier.
type RefreshTokenFunc func(context.Context, *ent.RefreshTokenQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RefreshTokenFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RefreshTokenQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RefreshTokenQuery", q)
}

// The TraverseRefreshToken type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRefreshToken func(context.Context, *ent.RefreshTokenQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRefreshToken) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRefreshToken) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RefreshTokenQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RefreshTokenQuery", q)
}

// The ResellerFunc type is an adapter to allow the use of ordinary function as a Querier.
type ResellerFunc func(context.Context, *ent.ResellerQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ResellerFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ResellerQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ResellerQuery", q)
}

// The TraverseReseller type is an adapter to allow the use of ordinary function as Traverser.
type TraverseReseller func(context.Context, *ent.ResellerQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseReseller) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseReseller) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ResellerQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ResellerQuery", q)
}

// The ResellerPlanFunc type is an adapter to allow the use of ordinary function as a Querier.
type ResellerPlanFunc func(context.Context, *ent.ResellerPlanQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ResellerPlanFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ResellerPlanQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ResellerPlanQuery", q)
}

// The TraverseResellerPlan type is an adapter to allow the use of ordinary function as Traverser.
type TraverseResellerPlan func(context.Context, *ent.ResellerPlanQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseResellerPlan) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseResellerPlan) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ResellerPlanQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ResellerPlanQuery", q)
}

// The SigningKeyFunc type is an adapter to allow the use of ordinary function as a Querier.
type SigningKeyFunc func(context.Context, *ent.SigningKeyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SigningKeyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SigningKeyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SigningKeyQuery", q)
}

// The TraverseSigningKey type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSigningKey func(context.Context, *ent.SigningKeyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSigningKey) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSigningKey) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SigningKeyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SigningKeyQuery", q)
}

// The SubscriberFunc type is an adapter to allow the use of ordinary function as a Querier.
type SubscriberFunc func(context.Context, *ent.SubscriberQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SubscriberFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SubscriberQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SubscriberQuery", q)
}

// The TraverseSubscriber type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSubscriber func(context.Context, *ent.SubscriberQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSubscriber) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSubscriber) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SubscriberQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SubscriberQuery", q)
}

// The UsagePlanFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsagePlanFunc func(context.Context, *ent.UsagePlanQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsagePlanFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsagePlanQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsagePlanQuery", q)
}

// The TraverseUsagePlan type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsagePlan func(context.Context, *ent.UsagePlanQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsagePlan) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsagePlan) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsagePlanQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsagePlanQuery", q)
}

// The UsageReportFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageReportFunc func(context.Context, *ent.UsageReportQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageReportFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageReportQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageReportQuery", q)
}

// The TraverseUsageReport type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageReport func(context.Context, *ent.UsageReportQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageReport) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageReport) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageReportQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageReportQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.AgentQuery:
		return &query[*ent.AgentQuery, predicate.Agent, agent.OrderOption]{typ: ent.TypeAgent, tq: q}, nil
	case *ent.ApiKeyQuery:
		return &query[*ent.ApiKeyQuery, predicate.ApiKey, apikey.OrderOption]{typ: ent.TypeApiKey, tq: q}, nil
	case *ent.DomainCertificateQuery:
		return &query[*ent.DomainCertificateQuery, predicate.DomainCertificate, domaincertificate.OrderOption]{typ: ent.TypeDomainCertificate, tq: q}, nil
	case *ent.EventQuery:
		return &query[*ent.EventQuery, predicate.Event, event.OrderOption]{typ: ent.TypeEvent, tq: q}, nil
	case *ent.NodeQuery:
		return &query[*ent.NodeQuery, predicate.Node, node.OrderOption]{typ: ent.TypeNode, tq: q}, nil
	case *ent.RefreshTokenQuery:
		return &query[*ent.RefreshTokenQuery, predicate.RefreshToken, refreshtoken.OrderOption]{typ: ent.TypeRefreshToken, tq: q}, nil
	case *ent.ResellerQuery:
		return &query[*ent.ResellerQuery, predicate.Reseller, reseller.OrderOption]{typ: ent.TypeReseller, tq: q}, nil
	case *ent.ResellerPlanQuery:
		return &query[*ent.ResellerPlanQuery, predicate.ResellerPlan, resellerplan.OrderOption]{typ: ent.TypeResellerPlan, tq: q}, nil
	case *ent.SigningKeyQuery:
		return &query[*ent.SigningKeyQuery, predicate.SigningKey, signingkey.OrderOption]{typ: ent.TypeSigningKey, tq: q}, nil
	case *ent.SubscriberQuery:
		return &query[*ent.SubscriberQuery, predicate.Subscriber, subscriber.OrderOption]{typ: ent.TypeSubscriber, tq: q}, nil
	case *ent.UsagePlanQuery:
		return &query[*ent.UsagePlanQuery, predicate.UsagePlan, usageplan.OrderOption]{typ: ent.TypeUsagePlan, tq: q}, nil
	case *ent.UsageReportQuery:
		return &query[*ent.UsageReportQuery, predicate.UsageReport, usagereport.OrderOption]{typ: ent.TypeUsageReport, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
