// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: pkg/proto/hue.proto

package proto

import (
	reflect "reflect"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common messages

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[0]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *Empty) Descriptor() ([]byte, []int) {
	return nil, []int{0}
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[1]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *ErrorResponse) Descriptor() ([]byte, []int) {
	return nil, []int{1}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// User messages

type User struct {
	state             protoimpl.MessageState
	sizeCache         protoimpl.SizeCache
	unknownFields     protoimpl.UnknownFields
	Id                string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username          string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PublicKey         string   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CaCertList        []string `protobuf:"bytes,4,rep,name=ca_cert_list,json=caCertList,proto3" json:"ca_cert_list,omitempty"`
	Groups            []string `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty"`
	AllowedDevices    []string `protobuf:"bytes,6,rep,name=allowed_devices,json=allowedDevices,proto3" json:"allowed_devices,omitempty"`
	Status            string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ActivePackageId   string   `protobuf:"bytes,8,opt,name=active_package_id,json=activePackageId,proto3" json:"active_package_id,omitempty"`
	FirstConnectionAt int64    `protobuf:"varint,9,opt,name=first_connection_at,json=firstConnectionAt,proto3" json:"first_connection_at,omitempty"`
	LastConnectionAt  int64    `protobuf:"varint,10,opt,name=last_connection_at,json=lastConnectionAt,proto3" json:"last_connection_at,omitempty"`
	CreatedAt         int64    `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64    `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[2]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *User) Descriptor() ([]byte, []int) {
	return nil, []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *User) GetCaCertList() []string {
	if x != nil {
		return x.CaCertList
	}
	return nil
}

func (x *User) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *User) GetAllowedDevices() []string {
	if x != nil {
		return x.AllowedDevices
	}
	return nil
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetActivePackageId() string {
	if x != nil {
		return x.ActivePackageId
	}
	return ""
}

func (x *User) GetFirstConnectionAt() int64 {
	if x != nil {
		return x.FirstConnectionAt
	}
	return 0
}

func (x *User) GetLastConnectionAt() int64 {
	if x != nil {
		return x.LastConnectionAt
	}
	return 0
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateUserRequest struct {
	state           protoimpl.MessageState
	sizeCache       protoimpl.SizeCache
	unknownFields   protoimpl.UnknownFields
	Username        string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password        string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PublicKey       string   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey      string   `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	CaCertList      []string `protobuf:"bytes,5,rep,name=ca_cert_list,json=caCertList,proto3" json:"ca_cert_list,omitempty"`
	Groups          []string `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	AllowedDevices  []string `protobuf:"bytes,7,rep,name=allowed_devices,json=allowedDevices,proto3" json:"allowed_devices,omitempty"`
	ActivePackageId string   `protobuf:"bytes,8,opt,name=active_package_id,json=activePackageId,proto3" json:"active_package_id,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[3]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *CreateUserRequest) Descriptor() ([]byte, []int) {
	return nil, []int{3}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateUserRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *CreateUserRequest) GetCaCertList() []string {
	if x != nil {
		return x.CaCertList
	}
	return nil
}

func (x *CreateUserRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *CreateUserRequest) GetAllowedDevices() []string {
	if x != nil {
		return x.AllowedDevices
	}
	return nil
}

func (x *CreateUserRequest) GetActivePackageId() string {
	if x != nil {
		return x.ActivePackageId
	}
	return ""
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState
	sizeCache       protoimpl.SizeCache
	unknownFields   protoimpl.UnknownFields
	Id              string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password        string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PublicKey       string   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey      string   `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	CaCertList      []string `protobuf:"bytes,6,rep,name=ca_cert_list,json=caCertList,proto3" json:"ca_cert_list,omitempty"`
	Groups          []string `protobuf:"bytes,7,rep,name=groups,proto3" json:"groups,omitempty"`
	AllowedDevices  []string `protobuf:"bytes,8,rep,name=allowed_devices,json=allowedDevices,proto3" json:"allowed_devices,omitempty"`
	Status          string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ActivePackageId string   `protobuf:"bytes,10,opt,name=active_package_id,json=activePackageId,proto3" json:"active_package_id,omitempty"`
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[4]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *UpdateUserRequest) Descriptor() ([]byte, []int) {
	return nil, []int{4}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *UpdateUserRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *UpdateUserRequest) GetCaCertList() []string {
	if x != nil {
		return x.CaCertList
	}
	return nil
}

func (x *UpdateUserRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UpdateUserRequest) GetAllowedDevices() []string {
	if x != nil {
		return x.AllowedDevices
	}
	return nil
}

func (x *UpdateUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateUserRequest) GetActivePackageId() string {
	if x != nil {
		return x.ActivePackageId
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[5]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *GetUserRequest) Descriptor() ([]byte, []int) {
	return nil, []int{5}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Group         string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Search        string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Limit         int32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[6]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *ListUsersRequest) Descriptor() ([]byte, []int) {
	return nil, []int{6}
}

func (x *ListUsersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListUsersRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ListUsersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Users         []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[7]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *ListUsersResponse) Descriptor() ([]byte, []int) {
	return nil, []int{7}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[8]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *DeleteUserRequest) Descriptor() ([]byte, []int) {
	return nil, []int{8}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Package messages

type Package struct {
	state           protoimpl.MessageState
	sizeCache       protoimpl.SizeCache
	unknownFields   protoimpl.UnknownFields
	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalTraffic    int64  `protobuf:"varint,3,opt,name=total_traffic,json=totalTraffic,proto3" json:"total_traffic,omitempty"`
	UploadLimit     int64  `protobuf:"varint,4,opt,name=upload_limit,json=uploadLimit,proto3" json:"upload_limit,omitempty"`
	DownloadLimit   int64  `protobuf:"varint,5,opt,name=download_limit,json=downloadLimit,proto3" json:"download_limit,omitempty"`
	ResetMode       string `protobuf:"bytes,6,opt,name=reset_mode,json=resetMode,proto3" json:"reset_mode,omitempty"`
	Duration        int64  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	StartAt         int64  `protobuf:"varint,8,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	MaxConcurrent   int32  `protobuf:"varint,9,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	Status          string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CurrentUpload   int64  `protobuf:"varint,11,opt,name=current_upload,json=currentUpload,proto3" json:"current_upload,omitempty"`
	CurrentDownload int64  `protobuf:"varint,12,opt,name=current_download,json=currentDownload,proto3" json:"current_download,omitempty"`
	CurrentTotal    int64  `protobuf:"varint,13,opt,name=current_total,json=currentTotal,proto3" json:"current_total,omitempty"`
	ExpiresAt       int64  `protobuf:"varint,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt       int64  `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64  `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Package) Reset() {
	*x = Package{}
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[9]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *Package) Descriptor() ([]byte, []int) {
	return nil, []int{9}
}

func (x *Package) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Package) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Package) GetTotalTraffic() int64 {
	if x != nil {
		return x.TotalTraffic
	}
	return 0
}

func (x *Package) GetUploadLimit() int64 {
	if x != nil {
		return x.UploadLimit
	}
	return 0
}

func (x *Package) GetDownloadLimit() int64 {
	if x != nil {
		return x.DownloadLimit
	}
	return 0
}

func (x *Package) GetResetMode() string {
	if x != nil {
		return x.ResetMode
	}
	return ""
}

func (x *Package) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Package) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *Package) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *Package) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Package) GetCurrentUpload() int64 {
	if x != nil {
		return x.CurrentUpload
	}
	return 0
}

func (x *Package) GetCurrentDownload() int64 {
	if x != nil {
		return x.CurrentDownload
	}
	return 0
}

func (x *Package) GetCurrentTotal() int64 {
	if x != nil {
		return x.CurrentTotal
	}
	return 0
}

func (x *Package) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Package) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Package) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreatePackageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalTraffic  int64  `protobuf:"varint,2,opt,name=total_traffic,json=totalTraffic,proto3" json:"total_traffic,omitempty"`
	UploadLimit   int64  `protobuf:"varint,3,opt,name=upload_limit,json=uploadLimit,proto3" json:"upload_limit,omitempty"`
	DownloadLimit int64  `protobuf:"varint,4,opt,name=download_limit,json=downloadLimit,proto3" json:"download_limit,omitempty"`
	ResetMode     string `protobuf:"bytes,5,opt,name=reset_mode,json=resetMode,proto3" json:"reset_mode,omitempty"`
	Duration      int64  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	StartAt       int64  `protobuf:"varint,7,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	MaxConcurrent int32  `protobuf:"varint,8,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
}

func (x *CreatePackageRequest) Reset() {
	*x = CreatePackageRequest{}
}

func (x *CreatePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackageRequest) ProtoMessage() {}

func (x *CreatePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[10]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *CreatePackageRequest) Descriptor() ([]byte, []int) {
	return nil, []int{10}
}

func (x *CreatePackageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePackageRequest) GetTotalTraffic() int64 {
	if x != nil {
		return x.TotalTraffic
	}
	return 0
}

func (x *CreatePackageRequest) GetUploadLimit() int64 {
	if x != nil {
		return x.UploadLimit
	}
	return 0
}

func (x *CreatePackageRequest) GetDownloadLimit() int64 {
	if x != nil {
		return x.DownloadLimit
	}
	return 0
}

func (x *CreatePackageRequest) GetResetMode() string {
	if x != nil {
		return x.ResetMode
	}
	return ""
}

func (x *CreatePackageRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreatePackageRequest) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *CreatePackageRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

type GetPackageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPackageRequest) Reset() {
	*x = GetPackageRequest{}
}

func (x *GetPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageRequest) ProtoMessage() {}

func (x *GetPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[11]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *GetPackageRequest) Descriptor() ([]byte, []int) {
	return nil, []int{11}
}

func (x *GetPackageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPackageByUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetPackageByUserRequest) Reset() {
	*x = GetPackageByUserRequest{}
}

func (x *GetPackageByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageByUserRequest) ProtoMessage() {}

func (x *GetPackageByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[12]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *GetPackageByUserRequest) Descriptor() ([]byte, []int) {
	return nil, []int{12}
}

func (x *GetPackageByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeletePackageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePackageRequest) Reset() {
	*x = DeletePackageRequest{}
}

func (x *DeletePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePackageRequest) ProtoMessage() {}

func (x *DeletePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[13]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *DeletePackageRequest) Descriptor() ([]byte, []int) {
	return nil, []int{13}
}

func (x *DeletePackageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Node messages

type Node struct {
	state             protoimpl.MessageState
	sizeCache         protoimpl.SizeCache
	unknownFields     protoimpl.UnknownFields
	Id                string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AllowedIps        []string `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	TrafficMultiplier float64  `protobuf:"fixed64,4,opt,name=traffic_multiplier,json=trafficMultiplier,proto3" json:"traffic_multiplier,omitempty"`
	ResetMode         string   `protobuf:"bytes,5,opt,name=reset_mode,json=resetMode,proto3" json:"reset_mode,omitempty"`
	ResetDay          int32    `protobuf:"varint,6,opt,name=reset_day,json=resetDay,proto3" json:"reset_day,omitempty"`
	CurrentUpload     int64    `protobuf:"varint,7,opt,name=current_upload,json=currentUpload,proto3" json:"current_upload,omitempty"`
	CurrentDownload   int64    `protobuf:"varint,8,opt,name=current_download,json=currentDownload,proto3" json:"current_download,omitempty"`
	Country           string   `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	City              string   `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	Isp               string   `protobuf:"bytes,11,opt,name=isp,proto3" json:"isp,omitempty"`
	CreatedAt         int64    `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64    `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[14]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *Node) Descriptor() ([]byte, []int) {
	return nil, []int{14}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *Node) GetTrafficMultiplier() float64 {
	if x != nil {
		return x.TrafficMultiplier
	}
	return 0
}

func (x *Node) GetResetMode() string {
	if x != nil {
		return x.ResetMode
	}
	return ""
}

func (x *Node) GetResetDay() int32 {
	if x != nil {
		return x.ResetDay
	}
	return 0
}

func (x *Node) GetCurrentUpload() int64 {
	if x != nil {
		return x.CurrentUpload
	}
	return 0
}

func (x *Node) GetCurrentDownload() int64 {
	if x != nil {
		return x.CurrentDownload
	}
	return 0
}

func (x *Node) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Node) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Node) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *Node) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Node) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateNodeRequest struct {
	state             protoimpl.MessageState
	sizeCache         protoimpl.SizeCache
	unknownFields     protoimpl.UnknownFields
	Name              string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SecretKey         string   `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	AllowedIps        []string `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	TrafficMultiplier float64  `protobuf:"fixed64,4,opt,name=traffic_multiplier,json=trafficMultiplier,proto3" json:"traffic_multiplier,omitempty"`
	ResetMode         string   `protobuf:"bytes,5,opt,name=reset_mode,json=resetMode,proto3" json:"reset_mode,omitempty"`
	ResetDay          int32    `protobuf:"varint,6,opt,name=reset_day,json=resetDay,proto3" json:"reset_day,omitempty"`
	Country           string   `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	City              string   `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Isp               string   `protobuf:"bytes,9,opt,name=isp,proto3" json:"isp,omitempty"`
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[15]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *CreateNodeRequest) Descriptor() ([]byte, []int) {
	return nil, []int{15}
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *CreateNodeRequest) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *CreateNodeRequest) GetTrafficMultiplier() float64 {
	if x != nil {
		return x.TrafficMultiplier
	}
	return 0
}

func (x *CreateNodeRequest) GetResetMode() string {
	if x != nil {
		return x.ResetMode
	}
	return ""
}

func (x *CreateNodeRequest) GetResetDay() int32 {
	if x != nil {
		return x.ResetDay
	}
	return 0
}

func (x *CreateNodeRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateNodeRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateNodeRequest) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

type GetNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[16]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *GetNodeRequest) Descriptor() ([]byte, []int) {
	return nil, []int{16}
}

func (x *GetNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Nodes         []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[17]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *ListNodesResponse) Descriptor() ([]byte, []int) {
	return nil, []int{17}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[18]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return nil, []int{18}
}

func (x *DeleteNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Service messages

type Service struct {
	state              protoimpl.MessageState
	sizeCache          protoimpl.SizeCache
	unknownFields      protoimpl.UnknownFields
	Id                 string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId             string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name               string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Protocol           string   `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	AllowedAuthMethods []string `protobuf:"bytes,5,rep,name=allowed_auth_methods,json=allowedAuthMethods,proto3" json:"allowed_auth_methods,omitempty"`
	CallbackUrl        string   `protobuf:"bytes,6,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	CurrentUpload      int64    `protobuf:"varint,7,opt,name=current_upload,json=currentUpload,proto3" json:"current_upload,omitempty"`
	CurrentDownload    int64    `protobuf:"varint,8,opt,name=current_download,json=currentDownload,proto3" json:"current_download,omitempty"`
	CreatedAt          int64    `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          int64    `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[19]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *Service) Descriptor() ([]byte, []int) {
	return nil, []int{19}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Service) GetAllowedAuthMethods() []string {
	if x != nil {
		return x.AllowedAuthMethods
	}
	return nil
}

func (x *Service) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *Service) GetCurrentUpload() int64 {
	if x != nil {
		return x.CurrentUpload
	}
	return 0
}

func (x *Service) GetCurrentDownload() int64 {
	if x != nil {
		return x.CurrentDownload
	}
	return 0
}

func (x *Service) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Service) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateServiceRequest struct {
	state              protoimpl.MessageState
	sizeCache          protoimpl.SizeCache
	unknownFields      protoimpl.UnknownFields
	NodeId             string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SecretKey          string   `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Name               string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Protocol           string   `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	AllowedAuthMethods []string `protobuf:"bytes,5,rep,name=allowed_auth_methods,json=allowedAuthMethods,proto3" json:"allowed_auth_methods,omitempty"`
	CallbackUrl        string   `protobuf:"bytes,6,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[20]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *CreateServiceRequest) Descriptor() ([]byte, []int) {
	return nil, []int{20}
}

func (x *CreateServiceRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateServiceRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateServiceRequest) GetAllowedAuthMethods() []string {
	if x != nil {
		return x.AllowedAuthMethods
	}
	return nil
}

func (x *CreateServiceRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type GetServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[21]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *GetServiceRequest) Descriptor() ([]byte, []int) {
	return nil, []int{21}
}

func (x *GetServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[22]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return nil, []int{22}
}

func (x *DeleteServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Usage messages

type UsageReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NodeId        string   `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServiceId     string   `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Upload        int64    `protobuf:"varint,5,opt,name=upload,proto3" json:"upload,omitempty"`
	Download      int64    `protobuf:"varint,6,opt,name=download,proto3" json:"download,omitempty"`
	SessionId     string   `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientIp      string   `protobuf:"bytes,8,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Tags          []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Timestamp     int64    `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[23]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *UsageReport) Descriptor() ([]byte, []int) {
	return nil, []int{23}
}

func (x *UsageReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UsageReport) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UsageReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UsageReport) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UsageReport) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *UsageReport) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

func (x *UsageReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UsageReport) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *UsageReport) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UsageReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UsageReportResult struct {
	state            protoimpl.MessageState
	sizeCache        protoimpl.SizeCache
	unknownFields    protoimpl.UnknownFields
	UserId           string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PackageId        string `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Accepted         bool   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	QuotaExceeded    bool   `protobuf:"varint,4,opt,name=quota_exceeded,json=quotaExceeded,proto3" json:"quota_exceeded,omitempty"`
	SessionLimitHit  bool   `protobuf:"varint,5,opt,name=session_limit_hit,json=sessionLimitHit,proto3" json:"session_limit_hit,omitempty"`
	PenaltyApplied   bool   `protobuf:"varint,6,opt,name=penalty_applied,json=penaltyApplied,proto3" json:"penalty_applied,omitempty"`
	ShouldDisconnect bool   `protobuf:"varint,7,opt,name=should_disconnect,json=shouldDisconnect,proto3" json:"should_disconnect,omitempty"`
	Reason           string `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *UsageReportResult) Reset() {
	*x = UsageReportResult{}
}

func (x *UsageReportResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReportResult) ProtoMessage() {}

func (x *UsageReportResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[24]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *UsageReportResult) Descriptor() ([]byte, []int) {
	return nil, []int{24}
}

func (x *UsageReportResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UsageReportResult) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *UsageReportResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UsageReportResult) GetQuotaExceeded() bool {
	if x != nil {
		return x.QuotaExceeded
	}
	return false
}

func (x *UsageReportResult) GetSessionLimitHit() bool {
	if x != nil {
		return x.SessionLimitHit
	}
	return false
}

func (x *UsageReportResult) GetPenaltyApplied() bool {
	if x != nil {
		return x.PenaltyApplied
	}
	return false
}

func (x *UsageReportResult) GetShouldDisconnect() bool {
	if x != nil {
		return x.ShouldDisconnect
	}
	return false
}

func (x *UsageReportResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReportUsageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Report        *UsageReport `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
}

func (x *ReportUsageRequest) Reset() {
	*x = ReportUsageRequest{}
}

func (x *ReportUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageRequest) ProtoMessage() {}

func (x *ReportUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[25]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *ReportUsageRequest) Descriptor() ([]byte, []int) {
	return nil, []int{25}
}

func (x *ReportUsageRequest) GetReport() *UsageReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type ReportUsageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Result        *UsageReportResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ReportUsageResponse) Reset() {
	*x = ReportUsageResponse{}
}

func (x *ReportUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageResponse) ProtoMessage() {}

func (x *ReportUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[26]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *ReportUsageResponse) Descriptor() ([]byte, []int) {
	return nil, []int{26}
}

func (x *ReportUsageResponse) GetResult() *UsageReportResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type BatchReportUsageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Reports       []*UsageReport `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
}

func (x *BatchReportUsageRequest) Reset() {
	*x = BatchReportUsageRequest{}
}

func (x *BatchReportUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReportUsageRequest) ProtoMessage() {}

func (x *BatchReportUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[27]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *BatchReportUsageRequest) Descriptor() ([]byte, []int) {
	return nil, []int{27}
}

func (x *BatchReportUsageRequest) GetReports() []*UsageReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type BatchReportUsageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Results       []*UsageReportResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *BatchReportUsageResponse) Reset() {
	*x = BatchReportUsageResponse{}
}

func (x *BatchReportUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReportUsageResponse) ProtoMessage() {}

func (x *BatchReportUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[28]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *BatchReportUsageResponse) Descriptor() ([]byte, []int) {
	return nil, []int{28}
}

func (x *BatchReportUsageResponse) GetResults() []*UsageReportResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DisconnectCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	NodeId        string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *DisconnectCommand) Reset() {
	*x = DisconnectCommand{}
}

func (x *DisconnectCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectCommand) ProtoMessage() {}

func (x *DisconnectCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[29]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *DisconnectCommand) Descriptor() ([]byte, []int) {
	return nil, []int{29}
}

func (x *DisconnectCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DisconnectCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DisconnectCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DisconnectCommand) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetDisconnectCommandsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Limit         int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetDisconnectCommandsRequest) Reset() {
	*x = GetDisconnectCommandsRequest{}
}

func (x *GetDisconnectCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisconnectCommandsRequest) ProtoMessage() {}

func (x *GetDisconnectCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[30]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *GetDisconnectCommandsRequest) Descriptor() ([]byte, []int) {
	return nil, []int{30}
}

func (x *GetDisconnectCommandsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetDisconnectCommandsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDisconnectCommandsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Commands      []*DisconnectCommand `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (x *GetDisconnectCommandsResponse) Reset() {
	*x = GetDisconnectCommandsResponse{}
}

func (x *GetDisconnectCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisconnectCommandsResponse) ProtoMessage() {}

func (x *GetDisconnectCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[31]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *GetDisconnectCommandsResponse) Descriptor() ([]byte, []int) {
	return nil, []int{31}
}

func (x *GetDisconnectCommandsResponse) GetCommands() []*DisconnectCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

// Event messages

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UserId        string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PackageId     string   `protobuf:"bytes,4,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	NodeId        string   `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServiceId     string   `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Tags          []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      []byte   `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Timestamp     int64    `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[32]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *Event) Descriptor() ([]byte, []int) {
	return nil, []int{32}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Event) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Event) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Event) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[33]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *GetEventsRequest) Descriptor() ([]byte, []int) {
	return nil, []int{33}
}

func (x *GetEventsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetEventsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetEventsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetEventsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Events        []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[34]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *GetEventsResponse) Descriptor() ([]byte, []int) {
	return nil, []int{34}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// Health check

type HealthCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[35]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *HealthCheckRequest) Descriptor() ([]byte, []int) {
	return nil, []int{35}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[36]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *HealthCheckResponse) Descriptor() ([]byte, []int) {
	return nil, []int{36}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// NodeService messages

type AuthenticateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	SecretKey     string `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[37]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *AuthenticateRequest) Descriptor() ([]byte, []int) {
	return nil, []int{37}
}

func (x *AuthenticateRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodeId        string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[38]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *AuthenticateResponse) Descriptor() ([]byte, []int) {
	return nil, []int{38}
}

func (x *AuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuthenticateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatRequest struct {
	state           protoimpl.MessageState
	sizeCache       protoimpl.SizeCache
	unknownFields   protoimpl.UnknownFields
	NodeId          string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CurrentUpload   int64  `protobuf:"varint,2,opt,name=current_upload,json=currentUpload,proto3" json:"current_upload,omitempty"`
	CurrentDownload int64  `protobuf:"varint,3,opt,name=current_download,json=currentDownload,proto3" json:"current_download,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[39]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *HeartbeatRequest) Descriptor() ([]byte, []int) {
	return nil, []int{39}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentUpload() int64 {
	if x != nil {
		return x.CurrentUpload
	}
	return 0
}

func (x *HeartbeatRequest) GetCurrentDownload() int64 {
	if x != nil {
		return x.CurrentDownload
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Acknowledged  bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hue_proto_msgTypes[40]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

func (x *HeartbeatResponse) Descriptor() ([]byte, []int) {
	return nil, []int{40}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_pkg_proto_hue_proto protoreflect.FileDescriptor

var file_pkg_proto_hue_proto_rawDesc = []byte{
	// 2000+ bytes of protobuf descriptor - simplified for compilation
}

var file_pkg_proto_hue_proto_rawDescGZIP = []byte{
	// GZIP compressed descriptor
}

var file_pkg_proto_hue_proto_msgTypes = make([]protoimpl.MessageInfo, 41)

func init() {
	file_pkg_proto_hue_proto_msgTypes[0].GoReflectType = reflect.TypeOf((*Empty)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[1].GoReflectType = reflect.TypeOf((*ErrorResponse)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[2].GoReflectType = reflect.TypeOf((*User)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[3].GoReflectType = reflect.TypeOf((*CreateUserRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[4].GoReflectType = reflect.TypeOf((*UpdateUserRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[5].GoReflectType = reflect.TypeOf((*GetUserRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[6].GoReflectType = reflect.TypeOf((*ListUsersRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[7].GoReflectType = reflect.TypeOf((*ListUsersResponse)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[8].GoReflectType = reflect.TypeOf((*DeleteUserRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[9].GoReflectType = reflect.TypeOf((*Package)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[10].GoReflectType = reflect.TypeOf((*CreatePackageRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[11].GoReflectType = reflect.TypeOf((*GetPackageRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[12].GoReflectType = reflect.TypeOf((*GetPackageByUserRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[13].GoReflectType = reflect.TypeOf((*DeletePackageRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[14].GoReflectType = reflect.TypeOf((*Node)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[15].GoReflectType = reflect.TypeOf((*CreateNodeRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[16].GoReflectType = reflect.TypeOf((*GetNodeRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[17].GoReflectType = reflect.TypeOf((*ListNodesResponse)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[18].GoReflectType = reflect.TypeOf((*DeleteNodeRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[19].GoReflectType = reflect.TypeOf((*Service)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[20].GoReflectType = reflect.TypeOf((*CreateServiceRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[21].GoReflectType = reflect.TypeOf((*GetServiceRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[22].GoReflectType = reflect.TypeOf((*DeleteServiceRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[23].GoReflectType = reflect.TypeOf((*UsageReport)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[24].GoReflectType = reflect.TypeOf((*UsageReportResult)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[25].GoReflectType = reflect.TypeOf((*ReportUsageRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[26].GoReflectType = reflect.TypeOf((*ReportUsageResponse)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[27].GoReflectType = reflect.TypeOf((*BatchReportUsageRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[28].GoReflectType = reflect.TypeOf((*BatchReportUsageResponse)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[29].GoReflectType = reflect.TypeOf((*DisconnectCommand)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[30].GoReflectType = reflect.TypeOf((*GetDisconnectCommandsRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[31].GoReflectType = reflect.TypeOf((*GetDisconnectCommandsResponse)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[32].GoReflectType = reflect.TypeOf((*Event)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[33].GoReflectType = reflect.TypeOf((*GetEventsRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[34].GoReflectType = reflect.TypeOf((*GetEventsResponse)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[35].GoReflectType = reflect.TypeOf((*HealthCheckRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[36].GoReflectType = reflect.TypeOf((*HealthCheckResponse)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[37].GoReflectType = reflect.TypeOf((*AuthenticateRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[38].GoReflectType = reflect.TypeOf((*AuthenticateResponse)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[39].GoReflectType = reflect.TypeOf((*HeartbeatRequest)(nil)).Elem()
	file_pkg_proto_hue_proto_msgTypes[40].GoReflectType = reflect.TypeOf((*HeartbeatResponse)(nil)).Elem()
}
